### ISSUE TITLE
Album art in KDE widgets

### ISSUE THREAD

**Issue by paulo-roger** [th-ch/youtube-music#1228] opened 2023-08-26 00:25 UTC
The album art do not show in the KDE/Gnome widget/extension

I have installed in two machines one with manjaro + gnome and the other with garuda + KDE and this happens on both of them.

When I open youtube in the browser or other players the art show normal, so I think this might be an API problem maybe?

let me know f you need debug info of some sort.

**Comment by JellyBrick** [comment] 2023-10-07 09:20
Duplicate of #1236

**Closed by JellyBrick** 2023-10-07 09:20 UTC
