### ISSUE TITLE
[Bug]: Discord's new rich presence doesn't seem to show playback time anymore

### ISSUE THREAD

**Issue by DereC4** [th-ch/youtube-music#2392] opened 2024-09-06 04:34 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.5.0

### Reproduction steps

![image](https://github.com/user-attachments/assets/4decba9b-4604-4dd8-addd-a9c1234e3717)

_fig. 1_

It appears that the new format isn't showing playback time with the discord plugin for this software enabled. Not sure why, it was showing the playback time fine 3 days ago but stopped since then.

### Expected Behavior

Playback time to show

### Actual Behavior

Playback time does not show

### Enabled plugins

Discord Rich Presence

**Comment by Dzheremi2** [comment] 2024-09-06 05:44
Duplicate of #2320

**Comment by DereC4** [comment] 2024-09-06 06:09
> Duplicate of #2320
ook

**Comment by JellyBrick** [comment] 2024-09-06 13:21
Duplicate of #2320

**Closed** 2024-09-06 13:21 UTC
