### ISSUE TITLE
[Bug]: Downloader returns error when trying to download a song in the app

### ISSUE THREAD

**Issue by ItsGittoDev** [th-ch/youtube-music#2701] opened 2024-12-11 22:53 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro Version 23H2 OS build 22631.4460 Windows Feature Experience Pack 1000.22700.1047.0

### What CPU architecture are you using?

x64

### Reproduction steps

1. Search a song
2. Enable the Download plugin
3. Right click the song
4. Click the download button in the drop menu

### Expected Behavior

The song downloads and goes into the specified download folder.

### Actual Behavior

I get a download error, either "unexpected token (x:xx)" or "The server responded with a non 2xx code in..."

![image](https://github.com/user-attachments/assets/d296ea53-16a8-4461-a0ab-54d9fe92545c)
![image](https://github.com/user-attachments/assets/fd5b7317-11d1-42e2-ad60-fb93f213e96d)

### Enabled plugins

1. In-app menu
2. Navigation
3. Playback Speed
4. Downloader
5. Discord Rich Presence

**Comment by ArtroxGabriel** [comment] 2024-12-11 23:01
I have the same error on my Linux system (6.11.10-2-MANJARO x86_64), installed via Paru.
I tried:
* Cleaning the app cache
* Reinstalling
* Cleaning up the config files and reinstalling the app

But it didn't work.

**Comment by JellyBrick** [comment] 2024-12-12 02:47
Please, read the `Preflight Checklist`.

Duplicate of #2691, #2628, #2700

**Closed by JellyBrick** 2024-12-12 02:47 UTC

**Comment by spoonh** [comment] 2024-12-17 22:04
https://github.com/th-ch/youtube-music/discussions/2726
