### ISSUE TITLE
[Bug]: Ads are playing when playing music from the Home Page

### ISSUE THREAD

**Issue by DereC4** [th-ch/youtube-music#2027] opened 2024-05-04 08:29 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.6.5

### Reproduction steps

1. Load plugin
2. From Home page, shuffle a song or playlist
3. On occasion (increasing more lately), an ad plays instead of the song. See behavior detailed below.

### Expected Behavior

The music tracks play without interruption from ads.

### Actual Behavior

![image](https://github.com/th-ch/youtube-music/assets/53978637/824aebe7-0fbb-49d8-97e7-4fddd33664e6)

Ads will show up for some reason. The ads can be skipped and disappear just as easily, but it is odd that they show up. Adblocker is enabled with the "in player" option, not "blocklists".

### Enabled plugins

1. Adblocker

**Comment by Siiyar** [comment] 2024-05-04 09:31
I have the same issue...

**Comment by garandal245** [comment] 2024-05-04 20:08
also happening for me

**Comment by DereC4** [comment] 2024-05-05 02:15
thx yall i thought i was alone on this

**Comment by JellyBrick** [comment] 2024-05-05 04:51
Duplicate of #1817 
PLEASE READ CHECKLISTS

**Closed by JellyBrick** 2024-05-05 04:51 UTC

**Comment by DereC4** [comment] 2024-05-05 09:13
> Duplicate of #1817 PLEASE READ CHECKLISTS

sounds like a plan!
