### ISSUE TITLE
[Bug]: Advertisement is not blocked

### ISSUE THREAD

**Issue by anishharam5** [th-ch/youtube-music#2024] opened 2024-05-02 18:13 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What CPU architecture are you using?

x64

### Reproduction steps

Just listen to music and make sure adblock is enabled
![image](https://github.com/th-ch/youtube-music/assets/38319227/72019fc7-2d34-41f4-894d-9724e5ea7dd8)

### Expected Behavior

To block ads 

### Actual Behavior

Not blocking ads

### Enabled plugins

Adblock

**Comment by derBobo** [comment] 2024-05-02 21:53
See #1817

**Comment by JellyBrick** [comment] 2024-05-04 06:57
Duplicate of #1817

**Closed by JellyBrick** 2024-05-04 06:57 UTC
