### ISSUE TITLE
[Feature Request]Add downloading bitrate settings

### ISSUE THREAD

**Issue by JimKatsanoss** [th-ch/youtube-music#643] opened 2022-03-12 13:46 UTC
As far as I can recall correctly, YouTube is able to play music @ 256 kbps. However, the downloader only downloads in 124kbps. Am I missing something or is it like that? If it is like that, is there any possibility that you could add bitrate options in the downloader? Thanks in advance<3

**Comment by Araxeus** [comment] 2022-03-12 14:29
currently it gets the highest available bitrate
https://github.com/th-ch/youtube-music/blob/5cffb6f06236c911843ae54757e2a242ffcf0ff6/plugins/downloader/youtube-dl.js#L60

but if you want, you can use [ffmpeg options](https://ffmpeg.org/ffmpeg-all.html) in config.json
https://github.com/th-ch/youtube-music/blob/5cffb6f06236c911843ae54757e2a242ffcf0ff6/config/defaults.js#L37

(Advanced options - edit config.json)

**Comment by JellyBrick** [comment] 2023-10-07 06:13
Duplicate of #226

**Closed by JellyBrick** 2023-10-07 06:13 UTC
Labels: duplicate
