### ISSUE TITLE
[Bug]: DMG doesnt open

### ISSUE THREAD

**Issue by scoobisofficial** [th-ch/youtube-music#2146] opened 2024-06-12 02:01 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Reproduction steps

1. Download DMG file
2. Doesnt open

### Expected Behavior

the installer would open

### Actual Behavior

installer dosent open

### Enabled plugins

N/A

**Comment by JellyBrick** [comment] 2024-06-12 10:33
Duplicate of #186

**Closed by JellyBrick** 2024-06-12 10:33 UTC

**Comment by scoobisofficial** [comment] 2024-06-12 19:13
After getting the DMG open, the file is damaged.

**Comment by kms0219kms** [comment] 2024-06-26 13:01
It is not damaged, check out #186 and MacOS section on the README. The command given should works well.
