### ISSUE TITLE
[Bug]: download error: Error: Unexpected token (1:71)

### ISSUE THREAD

**Issue by Fatbonks** [th-ch/youtube-music#2696] opened 2024-12-11 04:10 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What CPU architecture are you using?

x64

### Reproduction steps

1 enable downloader
2 try to download any song 
3 always comes up with the same error 
![Screenshot 2024-12-11 170632](https://github.com/user-attachments/assets/d37f552e-471c-4317-abb1-0a66a8cc14e1)
![Screenshot 2024-12-11 170702](https://github.com/user-attachments/assets/e5a24176-29b4-4c08-bb47-5c34c075dd9e)
i have removed all plugins expect downloader and have reinstalled yt music app

### Expected Behavior

should download songs without a token error

### Actual Behavior

any song displays a error when downloading

### Enabled plugins

downloader

**Comment by JellyBrick** [comment] 2024-12-11 04:28
Duplicate of #2691, #2628

![Screenshot](https://github.com/user-attachments/assets/30ef5cf5-d70e-42ad-96ff-824ea83a7b75)

**Closed by JellyBrick** 2024-12-11 04:28 UTC
Labels: duplicate
