### ISSUE TITLE
[Bug]: App start minimized and doesn't show up as a tray icon, music is played but no way to reach the UI

### ISSUE THREAD

**Issue by profnagol** [th-ch/youtube-music#2111] opened 2024-06-02 10:02 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

latest

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

previous version

### Reproduction steps

start the app

### Expected Behavior

Have a UI and a tray icon

### Actual Behavior

No UI or tray icon, although music is played in the background, only way to stop the app is task manager.

### Enabled plugins

Can't remember

**Comment by villne** [comment] 2024-06-02 13:18
I have same problem, only see and can close Youtube Music on taskmanager. The bug came when I updated from 3.3.8 to 3.3.9, same with latest 3.3.10. Windows 11 with latest updates.

**Comment by JellyBrick** [comment] 2024-06-03 10:04
Duplicate of #2113

**Closed by JellyBrick** 2024-06-03 10:04 UTC
