### ISSUE TITLE
[Bug]: Picture in Picture [ PIP ] Massive issue while PIPing a song , work fine with videos [ HOW NOBODY NOTICED ]

### ISSUE THREAD

**Issue by Zippu-4249** [th-ch/youtube-music#2615] opened 2024-11-18 20:04 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2 on Main pc and

### What CPU architecture are you using?

x64

### Reproduction steps

Simple just press P button on keyboard on a *song* . Not videos videos work perfectly and videos song image cover also works fine perfect 

### Expected Behavior

![Screenshot_151](https://github.com/user-attachments/assets/5de29ef6-8fe6-46a8-95e4-911676d9b779)

### Actual Behavior

![Screenshot_150](https://github.com/user-attachments/assets/0d0ffbe0-04d6-43ed-aef9-8db541c1aa2f)
![Screenshot_149](https://github.com/user-attachments/assets/2b8701df-47c3-4968-8e59-3d76f372b1e0)
![Screenshot_152](https://github.com/user-attachments/assets/b93f7681-00bf-4133-b419-74c96a2cca29)

### Enabled plugins

![image](https://github.com/user-attachments/assets/8019d637-b0da-4140-a4b9-6e47a9005189)

**Comment by JellyBrick** [comment] 2024-11-21 03:12
Duplicate of #1636

**Closed by JellyBrick** 2024-11-21 03:12 UTC
