### ISSUE TITLE
[Feature Request]: [ Romanization and Translation Lyrics ] Sorry for being annoying with same old Better Lyrics Extention Feature

### ISSUE THREAD

**Issue by ValiantZippu** [th-ch/youtube-music#2800] opened 2024-12-28 16:40 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

.

### Proposed Solution

If it is possible to get this kind of romanization and translation damnnnn this thing will be polisheeedd
![image](https://github.com/user-attachments/assets/6495e12d-5174-42c8-bff6-fa9b08a64725)
![image](https://github.com/user-attachments/assets/3e13c4f9-f018-4237-906e-74f77dcfa9e6)
![image](https://github.com/user-attachments/assets/199c4504-3ac6-4081-82c0-7d46681dc87b)
![image](https://github.com/user-attachments/assets/f8864265-2b5a-46dc-ae74-103a07010ac0)

Sorry for being annoying

### Alternatives Considered

.

**Comment by ValiantZippu** [comment] 2024-12-28 16:40
I am so sorry for being annoying

**Comment by ArjixWasTaken** [comment] 2024-12-28 16:53
https://github.com/th-ch/youtube-music/pull/2790 ....

**Comment by JellyBrick** [comment] 2024-12-28 22:51
READ PREFLIGHT CHECKLIST

Duplicate of #2775

**Closed by JellyBrick** 2024-12-28 22:51 UTC
