### ISSUE TITLE
[Bug]: sponsors not being blocked

### ISSUE THREAD

**Issue by Jeluxe** [th-ch/youtube-music#2040] opened 2024-05-09 14:04 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro Version	23H2 OS build 22631.3447

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

the one before

### Reproduction steps

play music,

### Expected Behavior

well no sponsor?!

### Actual Behavior

almost after every song there is sponsor

### Enabled plugins
```json
{
    "plugins": {
		"adblocker": {
			"enabled": true,
			"cache": true,
			"blocker": "In player",
			"additionalBlockLists": [],
			"disableDefaultLists": false
		},
		"album-color-theme": {
			"enabled": true
		},
		"compact-sidebar": {
			"enabled": true
		},
		"exponential-volume": {
			"enabled": true
		},
		"in-app-menu": {
			"enabled": true,
			"hideDOMWindowControls": false
		},
		"lyrics-genius": {
			"enabled": true,
			"romanizedLyrics": true
		},
		"navigation": {
			"enabled": true
		},
		"playback-speed": {},
		"precise-volume": {
			"enabled": true,
			"steps": "1",
			"arrowsShortcut": true,
			"globalShortcuts": {
				"volumeUp": "",
				"volumeDown": ""
			},
			"savedVolume": 46
		},
		"shortcuts": {
			"enabled": true,
			"overrideMediaKeys": true,
			"global": {
				"previous": "Ctrl+Alt+,",
				"playPause": "Ctrl+Alt+;",
				"next": "Ctrl+Alt+/"
			},
			"local": {
				"previous": "j",
				"playPause": "k",
				"next": "l"
			}
		},
		"skip-silences": {
			"onlySkipBeginning": false,
			"enabled": true
		},
		"sponsorblock": {
			"enabled": true,
			"apiURL": "https://sponsor.ajay.app",
			"categories": [
				"sponsor",
				"intro",
				"outro",
				"interaction",
				"selfpromo",
				"music_offtopic"
			]
		},
		"video-toggle": {
			"enabled": true,
			"hideVideo": true,
			"mode": "custom",
			"forceHide": true,
			"align": ""
		},
		"skip-disliked-songs": {
			"enabled": true
		},
		"album-actions": {
			"enabled": true
		},
	}
}
```

**Comment by ArjixWasTaken** [comment] 2024-05-09 16:25
By "sponsor" you mean "youtube ad" or "sponsored message within the video"?

**Comment by thehackedone** [comment] 2024-05-10 12:59
yes, the ads are no longer blocked for some reason

**Comment by nagarajpandith** [comment] 2024-05-10 19:19
+1

**Comment by kguzek** [comment] 2024-05-10 20:02
+1 experiencing the same thing. This wasn't an issue until now and I've used the app for like 3 years. Ads (as in normal YouTube ads you'd find on the official build) are being played before, during, after playback of songs. It seems like the adblocker has totally lost functionality.

**Comment by JustGregGithub** [comment] 2024-05-10 20:04
+1 on this too!

**Comment by ArjixWasTaken** [comment] 2024-05-10 22:35
duplicate of #1817

**Closed by ArjixWasTaken** 2024-05-10 22:35 UTC

**Comment by ArjixWasTaken** [comment] 2024-05-10 22:39
Please understand that if you want your issue resolved, don't open duplicate issues, put some effort into searching for the duplicate.

![image](https://github.com/th-ch/youtube-music/assets/53124886/31615e5f-cc58-4d58-9e28-76604026e056)

You lied in that image, you said you searched for a similar issue, a blatant lie.
Don't expect others to put any effort into fixing this if you yourself are not doing at least the bare minimum.

---

And for the people that comment `+1` please understand that you are not providing any value to the issue tracker, and are taking up screen real estate.

Please upvote the issue by a 👍 instead, that'd be much better.
