### ISSUE TITLE
[Bug]: False Positive Windows Defender Trojan:Win32/Cinjo.O!cl

### ISSUE THREAD

**Issue by Oosmus** [th-ch/youtube-music#2309] opened 2024-08-01 13:05 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.4.1

### Reproduction steps

Just run Youtube Music until Defender scans and quarantines the program. Takes about 5 minutes. Per Defender, Trojan:Win32/Cinjo.O!cl is the offending cause. 

### Expected Behavior

Prior to 3.5.0 (or 3.5.1) the program ran just fine. 

### Actual Behavior

The program runs for about 5 minutes and then is quarantined by windows defender. 

### Enabled plugins

1. Discord Rich Presence
2. In-App Menu
3. Navigation

**Comment by hammyongithub** [comment] 2024-08-01 15:01
Could it be related to this?

https://github.com/electron-userland/electron-builder/issues/5759

**Comment by JellyBrick** [comment] 2024-08-04 07:35
Duplicate of #1830

**Comment by JellyBrick** [comment] 2024-08-04 07:38
Duplicate of #1830

**Closed by JellyBrick** 2024-08-04 07:38 UTC
Labels: bug, electron-issue
