### ISSUE TITLE
Discord connection doesnt work anymore

### ISSUE THREAD

**Issue by ShyButterfly** [th-ch/youtube-music#925] opened 2022-12-20 14:28 UTC
everytime i press reconnect to the discord plugin, a popup message says "Connection failed | Connection closed"
after a reinstall, same issue

**Comment by KingPr0o7** [comment] 2022-12-20 23:36
Can also confirm. I remember it working on 1.16-1.17, but fails to connect on 1.18.

I wonder if some setting was introduced and interferes with Discord Plugin?

Here is a screenshot of that (1.18):
![Connection Failed](https://user-images.githubusercontent.com/64029396/208786018-33f6a584-f3a0-4aba-95fa-3760850f158d.png)

As well as the plugin settings for Discord Plugin (1.18):
![Discord Plugin Settings](https://user-images.githubusercontent.com/64029396/208786101-9f6f99f5-1ab1-47d3-96df-01026408cd1f.png)

**Comment by KingPr0o7** [comment] 2022-12-20 23:56
I've deleted my previous comment. Due to: this is a duplicate of: #895. 

Follow @Zo-Bro-23's steps here: [https://github.com/th-ch/youtube-music/issues/895#issuecomment-1327121950](url).

Works perfectly if you follow the steps!

Image Proof: 
![Proof of Discord RPC working!](https://user-images.githubusercontent.com/64029396/208788908-d92a9cb8-6b71-4d5d-a18c-b138e80cbfab.png)

**Comment by Zo-Bro-23** [comment] 2022-12-21 01:15
@KingPr0o7 sniped me to it!

You can also download a pre-built version from [here](https://github.com/Zo-Bro-23/youtube-music/releases) if you don't want to build the app yourself.

**Comment by Ruins4** [comment] 2022-12-23 10:59
> @KingPr0o7 sniped me to it!
> 
> You can also download a pre-built version from [here](https://github.com/Zo-Bro-23/youtube-music/releases) if you don't want to build the app yourself.

thanks dude!

**Comment by ShyButterfly** [comment] 2022-12-24 00:57
> @KingPr0o7 sniped me to it!
> 
> You can also download a pre-built version from [here](https://github.com/Zo-Bro-23/youtube-music/releases) if you don't want to build the app yourself.

Thank you so much dude ♥

**Closed** 2023-10-07 08:13 UTC
Labels: fix-available
