### ISSUE TITLE
[Bug]: Proxy doesn't work

### ISSUE THREAD

**Issue by TN141** [th-ch/youtube-music#2384] opened 2024-09-03 07:37 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 21H2

### What CPU architecture are you using?

x64

### Reproduction steps

0. You don't have access from your country
1. Check your proxy in other app;
2. Run app;
3. Set proxy to SOCKS5://username:password@ip:port
4. Restart application
5. "Cannot load YouTube Music… Internet disconnected?"

### Expected Behavior

The valid proxy is working

### Actual Behavior

"Cannot load YouTube Music… Internet disconnected?"

### Enabled plugins

1. SponsorBlock
2. Skip disliked music
3. No age restriction
4. Navigation
5. App menu

### Additional Information

The proxy is 100% working. This is my personal one and I checked it in another app.

**Comment by ArjixWasTaken** [comment] 2024-09-03 07:59
Chromium issue.
You cannot set username:password like that.

**Comment by TN141** [comment] 2024-09-03 09:47
@ArjixWasTaken thanks for fast reply :) How should it be?

**Comment by ArjixWasTaken** [comment] 2024-09-03 09:51
with the way things are, you can't set a username/password for a proxy

**Comment by JellyBrick** [comment] 2024-09-03 10:37
Duplicate of #743

**Closed by JellyBrick** 2024-09-03 10:37 UTC

**Comment by TN141** [comment] 2024-09-03 17:57
I'm use 3proxy:

My config `3proxy.cfg`:
```
fakeresolve

nserver 8.8.8.8
nserver 8.8.4.4

auth iponly
allow * 127.0.0.1,192.168.100.0/2
parent 100 connect <real_ip> <real_port> user <login> <password>

#allow * 127.0.0.1,192.168.100.0/2
parent 100 http <real_ip> <real_port> user <login> <password>

proxy -p<fake_port>

allow *
socks
```
