### ISSUE TITLE
[Feature Request] Synchronised play across devices/remote control.

### ISSUE THREAD

**Issue by Ansis100** [th-ch/youtube-music#771] opened 2022-07-01 08:44 UTC
I have no idea if this is possible but it's the feature I miss the most from Spotify.
The most typical use case is to use your phone as a remote for the PC.

I'm guessing it would be much easier with a dedicated server on the PC and a custom app on the phone. I'm just wondering if it can be done via this app.

**Comment by DerTyp7214** [comment] 2022-07-10 19:20
Hi, I implemented in a [fork](https://github.com/DerTyp7214/youtube-music) the remote functionality and published a remote application in [google playstore](https://play.google.com/store/apps/details?id=de.dertyp7214.youtubemusicremote)
I dont know i will ever really finish this implementation to merge it in here. but you can use the forked version

**Comment by Ansis100** [comment] 2022-07-14 08:41
Just tested it, works absolutely fantastic, thank you for this!
I wish my watch music control didn't prioritise YTM mobile and instead would control your app, buuuut beggars can't be choosers.
Also, I had to disable the VirtualBox virtual network adapter so the desktop app would choose the Wi-Fi adapter. Would be nice if you could choose a network interface. Even better, set a manual IP and port which would work great if you have a static public IP.

**Comment by DerTyp7214** [comment] 2022-07-14 09:08
thanks for the suggestions, i implemented custom port and to choose network interface in popup. for further request feel free to open issues/pull requests

**Comment by Araxeus** [comment] 2023-02-25 22:24
@DerTyp7214 when are you planning to merge back?

**Comment by DerTyp7214** [comment] 2023-02-25 22:34
> @DerTyp7214 when are you planning to merge back?

I dont know if i will, since i think my code is somewhat hacky/unclean. It works mostly for me, but i dont want to merge something im not completely happy with. But if you want you can use my code, i dont mind it.
Other thing, i dont really maintain the android app i created to controll the desktop programm anymore, just sometimes if something bothers me.
If you want i can give you permission to the app repo, it has a workflow to publish a new release.

**Comment by Zo-Bro-23** [comment] 2023-02-26 02:57
I'm working on a similar feature that enables a REST API for songInfo and songControls. I am also working on an Android app for the same. Can I take this up? You can assign the issue to me.

**Comment by Zo-Bro-23** [comment] 2023-03-31 02:47
Will be fixed by #1094.

**Comment by Marcel13078** [comment] 2023-08-31 22:35
Hello i wanted to ask if there are any Updates for this topic since i had the same idea to ask

**Comment by JellyBrick** [comment] 2023-10-07 09:25
Duplicate of #739

**Closed by JellyBrick** 2023-10-07 09:25 UTC
