### ISSUE TITLE
Replace pulseaudio default name "chromium" to unique name

### ISSUE THREAD

**Issue by zapata111** [th-ch/youtube-music#722] opened 2022-05-18 13:35 UTC
In pulseaudio audio the app is named chromium, and as I change the audio for a specific output audio device, all chomium will be played at that output audio device. Please add a unique name, by setting **media::AudioManager::SetGlobalAppName** as referenced here: https://github.com/electron/electron/issues/7470

**Comment by Araxeus** [comment] 2022-05-18 15:23
duplicate of #523 

Electron needs to fix this themselves, I suggest leaving a comment on the issue https://github.com/electron/electron/issues/27581

[also it seems discord acts the same](https://www.reddit.com/r/linuxquestions/comments/nbjmo5/why_do_pulseaudio_and_pipewire_see_discord_as/)

**Closed** 2023-10-09 13:22 UTC
Labels: duplicate
