### ISSUE TITLE
[Bug]:the server responded with a non 2 XX status code

### ISSUE THREAD

**Issue by TheBlackJack22** [th-ch/youtube-music#2801] opened 2024-12-28 20:19 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.7.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

11latest

### What CPU architecture are you using?

x64

### Reproduction steps

![image](https://github.com/user-attachments/assets/5efd810f-091d-479d-a25e-a98ff8cda887)

### Expected Behavior

I click the download button but it throws an error

### Actual Behavior

I click the download button but it throws an error

### Enabled plugins

1.downloader

### Additional Information

I did everything please help me somebody

**Comment by TheBlackJack22** [comment] 2024-12-28 20:21
I'm really tired of the downloader not working it's the only reason I use your program

**Comment by JellyBrick** [comment] 2024-12-28 22:49
READ PREFLIGHT CHECKLIST

Duplicate of #2780

**Closed by JellyBrick** 2024-12-28 22:49 UTC
