### ISSUE TITLE
download song

### ISSUE THREAD

**Issue by senolfndk** [th-ch/youtube-music#2718] opened 2024-12-15 06:23 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

windows 11 pro 24H2

### What CPU architecture are you using?

x64

### Reproduction steps

song download not working

### Expected Behavior

song download not working

### Actual Behavior

song download not working

### Enabled plugins

album actions

### Additional Information

![Ekran görüntüsü 2024-12-15 092144](https://github.com/user-attachments/assets/93722eb0-9d79-4ea3-ac82-66ede11c44c3)

**Comment by KParthSingh** [comment] 2024-12-15 10:14
Came here to just report this issue.

**Comment by IphoneCake** [comment] 2024-12-15 12:10
Have the same Problem Unexpected Token (1:71)

**Comment by JellyBrick** [comment] 2024-12-15 12:52
READ THE PREFLIGHT CHECKLIST

Duplicate of https://github.com/th-ch/youtube-music/issues/2691, https://github.com/th-ch/youtube-music/issues/2628

**Closed by JellyBrick** 2024-12-15 12:52 UTC

**Comment by spoonh** [comment] 2024-12-17 22:03
https://github.com/th-ch/youtube-music/discussions/2726

**Comment by senolfndk** [comment] 2024-12-19 13:50
https://github.com/user-attachments/assets/d068a1dc-f7dd-4c85-a903-0d7a1a53c1b5

**Comment by KParthSingh** [comment] 2024-12-19 13:53
> Ekran.Kaydi.2024-12-19.164824.mp4

The developer is aware of the problem. THey said they'll release a fix within a week.

**Comment by senolfndk** [comment] 2024-12-25 04:06
Same problem again

**Comment by senolfndk** [comment] 2024-12-25 04:06
bypass age verification not working

**Comment by senolfndk** [comment] 2024-12-26 18:38
![Ekran görüntüsü 2024-12-26 213719](https://github.com/user-attachments/assets/7d65386e-baad-4ad3-bfac-2f94dacecc32)
