### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by probonopd** [th-ch/youtube-music#1] opened 2019-04-21 06:51 UTC
Uncaught exception:

![](https://github.com/AppImage/appimage.github.io/blob/1049efb1dc6dd3c643ac44bd380aeb81b3522032/database/youtube-music/screenshot.png?raw=true)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1479

**Comment by th-ch** [comment] 2019-04-28 15:36
Thank you for reporting the bug. This was caused by the native module [ad-block](https://github.com/brave/ad-block) that needs to be re-compiled on each platform.

Releasing has been changed to re-compile modules and build on AppVeyor (Windows) and Travis (Mac/Linux), the [1.1.1 release](https://github.com/th-ch/youtube-music/releases/tag/v1.1.1) should fix the issue (tested on Ubuntu 18.10).

Closing this issue, feel free to re-open if needed.

**Closed by th-ch** 2019-04-28 15:36 UTC

**Comment by probonopd** [comment] 2019-04-29 18:34
Thanks. Now I am only getting a black screen. What is the expected behavior when there is no internet connectivity?

**Comment by th-ch** [comment] 2019-05-01 18:21
Indeed, the app has no offline mode, and no internet connectivity would result in a black screen (default background color). 
-> to have a better UX, I added an error message + *retry* button when the page fails to load in the [latest version (1.1.2)](https://github.com/th-ch/youtube-music/releases/tag/v1.1.2):

<img width="599" alt="youtube-music-error" src="https://user-images.githubusercontent.com/8024624/57031475-207cb680-6c48-11e9-9840-b31df3f5b269.png">

Thank you for the feedback and feel free to reach out if you find other issues!
