### ISSUE TITLE
[Feature Request]: Auto-updater

### ISSUE THREAD

**Issue by lightcatdev** [th-ch/youtube-music#2324] opened 2024-08-02 21:17 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Whenever you have to update the app, you have to manually go to github to update the app.

### Proposed Solution

Instead of bringing you to the repo, it should automatically update the app by downloading the files from github and restart the app automatically.

### Alternatives Considered

You could also make it so instead of just bringing you to the repo, it would bring you to the download link automatically, so it would just download when you click download.

**Comment by JellyBrick** [comment] 2024-08-04 07:45
Duplicate of #1347

**Closed by JellyBrick** 2024-08-04 07:45 UTC
