### ISSUE TITLE
[Bug]: Latest Version v3.3.4 having weird audio issues! 

### ISSUE THREAD

**Issue by JoqniX** [th-ch/youtube-music#1888] opened 2024-03-26 06:48 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.4.0

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro Version	23H2 |  OS build - 22631.3296 

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

v3.3.3

### Reproduction steps

Refer the Enabled Plugins section! 
enable the same exact plugins i have enabled. 
try playing a song. and wait till crossfade happens
alt tab or change window size etc. do anything you want ( as this is random and i cannot predict when this bug occurs)

Remember if this bug occurs. the best possible way to fix it is to quit the app. and relaunch it. everytime this occurs! 

### Expected Behavior

regardless of what all plugins are enabled. it is supposed to emit audio if a song/track is being played. 
everything was working fine on previous version. 

### Actual Behavior

as of writing of this issue. im currently experiencing this. 
it played song 1. and after transition to song 2. it completely became silent. but the song is still playing. 
it is possible that crossfade plugin had something happen? due to the latest update?? 

***Update**
so i noticed a weird bug right now. 
so the song i was playing - was 7 mins. the audio only emited after 6min mark.??? but the audio emitted was beginning start of the song.
cuz of the crossfade plugin enabled. as the song was ending ( but emiting audio from start of the song) it force skipped to the next song. 
here. the 2nd song is completely inaudiable. i tried to seek it by manually clicking. it only emited audio at the last part. 
when the last part's audio was emited. i click on the start of the song and it somehow miraculously started to play and emit audio properly? ( but this sometimes works but doesnt work)  

### Enabled plugins

1. Album Actions
2. Audio Compressor
3. Blur Navigation Bar
4. Compact Sidebar
5. Exponential Volume
6. In-App Menu
7. Music Together
8. Navigation
9. Taskbar Media Control
10. Tuna OBS
11. Video Quality Changer
12. Crossfade
13. Picture-in-Picture
14. Precise Volume
15. Scrobbler ( lastfm)
16. Discord Rich Presence
17. Notifications ( style > Hero)

### Additional Information

i shall try to record a video of this! i hope this can be helpful! do watch the video carefully. to notice a couple of issues.
also sorry i did this recording in window capture. i should have used display capture to record it. but yea i hope atleast this works? to understand the issue?

**Link to the Recording -** https://drive.google.com/file/d/1mtR0fXdg2qjYyyZSIIO2BxLfoIR2g7ip/view?usp=drive_link 

** Update **
like wow. as per the recording you can see, changing the volume fixes? this issue? ehhh. what is going on?? 
i think its due to Crossfade. but sometimes i feel like its not crossfade??? crossfade is working correctly as intended. but its just the audio..

**Comment by JellyBrick** [comment] 2024-03-26 09:24
Duplicate of #1775

**Closed by JellyBrick** 2024-03-26 09:24 UTC
