### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Toorero** [th-ch/youtube-music#1695] opened 2024-01-29 17:16 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2-1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Archlinux

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable Discord Plugin

### Expected Behavior

1. Ask to connect to Discord
2. The Discord RPC should show up in my profile status.

### Actual Behavior

Nothing shows up in my profile status nor am I asked to connect anything but in the plugin there is a checkmark for connected.

### Enabled plugins

- precise-volume
- discord
- album-color-theme
- lyrics-genius
- crossfade
- ambient-mode
- picture-in-picture
- exponential-volume
- visualizer

### Additional Information

I suspect that I have to install the Discord app because of the question asked in #1664. Is there a workaround where I don't have to install Discord, since I'm using [Webcord](https://github.com/SpacingBat3/WebCord)

**Comment by JellyBrick** [comment] 2024-01-30 00:08
Duplicate of #1664,
and `WebCord` does not support Discord RPC.
see https://github.com/SpacingBat3/WebCord/issues/292

**Closed by JellyBrick** 2024-01-30 00:08 UTC
