### ISSUE TITLE
Stuck at "Downloading..."

### ISSUE THREAD

**Issue by Hdacc** [th-ch/youtube-music#798] opened 2022-08-20 14:10 UTC
Not sure if it is just me but tracks have not been downloading and is stuck at "downloading...", tried to uninstall and reinstall, still the same.

![Downloading](https://user-images.githubusercontent.com/72586962/185750323-62475bec-9ba8-4e38-8f85-5dc3627612f1.png)

**Comment by nyanitsu** [comment] 2022-08-21 14:07
I am facing this issue as well, both on linux and windows

**Comment by th-ch** [comment] 2022-08-21 21:11
Hey folks, issue is confirmed indeed and seems to be https://github.com/fent/node-ytdl-core/issues/1113 - a fix PR is open (https://github.com/fent/node-ytdl-core/pull/1111), if it gets merged quickly I'll update the package, otherwise downgrading to 4.10 seems to work, it can be a fallback option if the fix is not merged upstream - thanks for reporting, stay tuned for the fix! (keeping the issue open in the meantime)

**Comment by Araxeus** [comment] 2022-09-03 19:34
@th-ch 4.11.1 apparently solves this following https://github.com/fent/node-ytdl-core/pull/1126

**Closed** 2022-09-05 06:45 UTC
