### ISSUE TITLE
[Bug]: Sound quality lost after v.1.19.0

### ISSUE THREAD

**Issue by Dagmayer** [th-ch/youtube-music#1579] opened 2024-01-01 22:51 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

1.19.0 , 1.20.0 , 2.20 , 3.2.1

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22621.2861

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

1.19.0

### Reproduction steps

Audio distortion on v.1.20.0 or above with default settings

### Expected Behavior

-

### Actual Behavior

-

### Enabled plugins

Adblocker
Bypass-age-restriction
Sponsorblock
Skip-silences
Taskbar-media-control
Navigation
Quality-changer

### Additional Information

All versions above 1.19.0 have sound distortion on my system (ASUS N56VZ with 2.1ch), namely: the bass is gone, a grinding sound appears at high frequencies, and the sound periodically freezes.
The problem is definitely not related to the driver/system/hardware: everything has been repeatedly checked in any other applications, OS, with other drivers, sound output quality, equalizers, etc. Your app installation is always clean.
I periodically checked the changes when newer versions were released (starting with 1.20.0 and ending with the recent 3.2.1), the problem remains with version 1.20.0, On 1.19.0 and below everything works wonderfully.
I love your app and want to stay on it.
Can we somehow solve the problem? I get full feedback, logs, etc.

**Comment by JellyBrick** [comment] 2024-01-02 08:31
Can you try deactivating the Skip-silences plugin?

**Comment by JellyBrick** [comment] 2024-01-02 08:40
https://github.com/th-ch/youtube-music/commit/52b67af59c30e6148f00a485e25ebc8653ce7936

Perhaps this commit is causing this issue.

**Comment by Rairof** [comment] 2024-01-03 14:41
https://github.com/th-ch/youtube-music/issues/1579#issuecomment-1873732412
I tried and yes it was causing the audio quality issue, audio quality is fine when it is disabled

**Comment by Dagmayer** [comment] 2024-01-03 17:43
> Can you try deactivating the `skip-silences` plugin?

Yes, after deactivating this plugin, the sound quality is now the same as on version 1.19.0. Thank you (:

**Comment by inson1** [comment] 2024-01-03 19:13
so duplicate of #1141 with some added info

**Closed** 2024-01-03 20:12 UTC
Labels: bug
