### ISSUE TITLE
LastFM album scrobbling not working correctly.

### ISSUE THREAD

**Issue by stupidandrew** [th-ch/youtube-music#1006] opened 2023-01-28 18:51 UTC
I use pano scrobbler on my phone and it tells me what from what album the song is.

The problem is that most of the times the album just doesn't appear or uses the album from the last song played.

I've tried looking into the settings but just couldn't find anything.

**Comment by Araxeus** [comment] 2023-01-28 19:37
duplicate of #957 #806 #540 #902 #744

**Closed** 2023-03-14 15:18 UTC
