### ISSUE TITLE
[Bug]: Does not render the graphical interface

### ISSUE THREAD

**Issue by Vik-Fx** [th-ch/youtube-music#1324] opened 2023-10-16 12:25 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.1.1

### What operating system are you using?

Other Linux

### Operating System Version

Debian 12 SID

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

1.20.0

### Expected Behavior

graphical interface

### Actual Behavior

![2023-10-16_20-17](https://github.com/th-ch/youtube-music/assets/125733774/1696127e-1ab6-46eb-b692-ce9c693e4a5f)

The application window looks like this. It plays tracks, but does not display them.

**Comment by JellyBrick** [comment] 2023-10-16 12:30
It does not seem to be a issue with the YTM application. check your graphics card drivers and window manager.

**Comment by Vik-Fx** [comment] 2023-10-16 12:43
![2023-10-16_20-40](https://github.com/th-ch/youtube-music/assets/125733774/3e6493c2-b5d9-4d10-b4ff-180025f7ae9b)

Downgrade to version 1.20.0

**Comment by JellyBrick** [comment] 2023-10-16 12:55
It seems to be an issue with Electron.
Could you provide more hardware information, WM information, and display driver information?

**Comment by Vik-Fx** [comment] 2023-10-16 13:00
Debian GNU/Linux trixie/sid
AMD Radeon Pro WX 5100 Graphics
Mesa VA drivers 23.2.1-1
Gnome 44.5
Linux 6.5.0-2-amd64

**Comment by JellyBrick** [comment] 2023-10-16 13:26
Forwarded to https://github.com/electron/electron/issues/40223

**Comment by JellyBrick** [comment] 2023-10-17 12:58
> ![2023-10-17_20-41](https://user-images.githubusercontent.com/125733774/275838531-215514ba-ff46-4ab4-8102-ccdbe1d90953.png)
> 
> Experimentally, a package was found that leads to this problem libllvm16 1:16.0.6-16 Downgrade to version libllvm16 1:16.0.6-15 solves the problem.

Could you post it to electron/electron#40223?

**Comment by JellyBrick** [comment] 2023-10-18 16:13
can you reproduce this in Google Chrome itself, without Electron? You'll need to ensure your version of Chrome is at least 118.0.5993.54.

Original comment: https://github.com/electron/electron/issues/40223#issuecomment-1768773658

**Comment by Vik-Fx** [comment] 2023-10-19 06:20
![2023-10-19_14-03_1](https://github.com/th-ch/youtube-music/assets/125733774/80c8cd4a-08a6-4b8a-b23a-57a00efc2908)

libllvm16 1:16.0.6-15
YouTube Music version 2.1.1
Chrome Version 118.0.5993.88

The application works correctly.
It works correctly in the browser.

**Comment by Vik-Fx** [comment] 2023-10-19 06:23
Updated libllvm16 1:16.0.6-16

YouTube Music version 2.1.1
![2023-10-19_14-04](https://github.com/th-ch/youtube-music/assets/125733774/bfc6ef58-08b2-4641-8257-889724de6a53)

Chrome Version 118.0.5993.88
![2023-10-19_14-06](https://github.com/th-ch/youtube-music/assets/125733774/98cb4ccc-9c66-499e-ac25-ba1cc66d962b)

It works correctly in the browser.

**Comment by JellyBrick** [comment] 2023-10-19 13:48
Are you still having this issue in 2.1.2?

**Comment by Vik-Fx** [comment] 2023-10-19 14:56
libllvm16 1:16.0.6-16
YouTube Music version 2.1.2

![2023-10-19_22-38](https://github.com/th-ch/youtube-music/assets/125733774/2e7c6d84-62a2-4b95-a731-3cb68c9d7bb4)

without changes

**Comment by Vik-Fx** [comment] 2023-10-21 13:59
Upgrade to version: libllvm16 1:16.0.6-17 also breaks the interface.

**Comment by JellyBrick** [comment] 2023-11-08 22:51
see https://bugs.chromium.org/p/chromium/issues/detail?id=1442633

Notes: This bug is fixed in electron v27.0.4.

**Comment by JellyBrick** [comment] 2023-11-09 01:40
Are you still experiencing this issue with 269352a?

**Comment by JellyBrick** [comment] 2023-11-09 01:40
@Vik-Fx Are you still experiencing this issue with 269352a?

**Closed** 2023-11-09 01:39 UTC
Labels: bug, electron-issue
