### ISSUE TITLE
[Bug]: Automatically logged out

### ISSUE THREAD

**Issue by Mefiseru** [th-ch/youtube-music#2117] opened 2024-06-03 00:32 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.10

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22631 (23H2)

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

I think it was 2.2.0

### Reproduction steps

Tap the login button, login into account (using phone), you will be redirected to google manage account page. Reload app or just head to main page and you'll be instantly logged out.
Same happens to me with password login too.

### Expected Behavior

It must stay logged in

### Actual Behavior

It's logging out without any information.

### Enabled plugins

1. Adblock
2. Menu in APP
3. Navigation

**Comment by JellyBrick** [comment] 2024-06-03 10:00
See https://github.com/th-ch/youtube-music/issues/1753#issuecomment-2119283636

**Comment by JellyBrick** [comment] 2024-06-03 10:01
Duplicate of #1753

**Closed by JellyBrick** 2024-06-03 10:01 UTC

**Comment by Mefiseru** [comment] 2024-06-06 19:44
> Duplicate of #1753

Well, this doesn't fix a CLEAR bug in a system, rather this a duplicate or not.
