### ISSUE TITLE
[Bug]: when in full screen there is a big gap in the top pushing part of the video to be cropped by the screen

### ISSUE THREAD

**Issue by Elshalomkibru** [th-ch/youtube-music#2055] opened 2024-05-16 07:24 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

windows 11 home

### What CPU architecture are you using?

x64

### Reproduction steps

1. open the app
2. open a video
3. put in full screen

### Expected Behavior

the video to play in full screen with out no gaps on the screen

### Actual Behavior

even tho the vedio size is compatible with my screen dimensions the video always pushes down leaving a gap on the top and croping it on the bottom

### Enabled plugins

1. ad blocker

**Comment by JellyBrick** [comment] 2024-05-25 00:08
Duplicate of #2051

**Closed by JellyBrick** 2024-05-25 00:08 UTC
