### ISSUE TITLE
[Bug]: ads block

### ISSUE THREAD

**Issue by CheemsGalaxy** [th-ch/youtube-music#2223] opened 2024-07-12 06:14 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

2.0.0

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

win10 ver22h2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

1.20.0

### Reproduction steps

1. I have turned on ad blocking but sometimes the sound calling to buy youtube pre is still there

### Expected Behavior

application still have ads  

### Actual Behavior

ads

### Enabled plugins

ads blocker

**Comment by Tarangit1** [comment] 2024-07-12 09:08
I was having same issue but came back after few hours its working fine now
you can try enabling this
![image](https://github.com/user-attachments/assets/d9cce8ca-db04-4c84-b50b-7cc4d3e17ca7)

**Comment by JellyBrick** [comment] 2024-07-13 02:27
Duplicate of #2150

**Closed by JellyBrick** 2024-07-13 02:27 UTC
