### ISSUE TITLE
[Bug]: Error unexpected token (1:71)

### ISSUE THREAD

**Issue by tomas293** [th-ch/youtube-music#2691] opened 2024-12-09 19:46 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.6.2.0

### Reproduction steps

Change download folder
Disable Visualizer
Download

i reinstalled the program the issue persists

### Expected Behavior

Download song

### Actual Behavior

![image](https://github.com/user-attachments/assets/93b5d256-1020-4eab-88f2-b562ff7efbd2)
on all song music videos/audios

### Enabled plugins

1. Visualizer
2. Exponential Volume
3. In app menu 
4. Lumia Stream
5. Navigation
6. Video Toggle
7. Synced Lyrics
8. Lyrics Genius
9. Downloader
10. Add blocker
11. Ambient Mode

### Additional Information

Writes the error in the image above and doesn't download

**Comment by b3hr3nss** [comment] 2024-12-09 20:55
Having the same issue on both of my computers (W10 on one, W11) the other.

Tried reinstalling, and the last 5 or 6 portable versions.

**Comment by JellyBrick** [comment] 2024-12-10 03:03
Duplicate of #2628

**Closed by JellyBrick** 2024-12-10 03:03 UTC

**Comment by spoonh** [comment] 2024-12-19 22:32
https://github.com/th-ch/youtube-music/discussions/2726
