### ISSUE TITLE
[Feature Request] Chromecast support

### ISSUE THREAD

**Issue by playday3008** [th-ch/youtube-music#289] opened 2021-05-17 22:41 UTC
Cast as YouTube Music (as smartphone version)
Or cast as "tab" (as Chrome/Edge etc.)

**Comment by Araxeus** [comment] 2021-05-17 23:13
I will try working on that, but only if you are prepared to test it out abit when its ready,
because I dont personally have one 😅

**Comment by playday3008** [comment] 2021-05-18 11:09
No problem

**Comment by Araxeus** [comment] 2021-05-18 20:49
Ok here is the first draft version: 
https://github.com/Araxeus/youtube-music/tree/chromecast

Its on a branch in my fork. can you clone and run `yarn start` on it?
> run `yarn install` before launching to install new dependencies

if not, and you are using windows - I can build and upload binaries for you if needed

After enabling the plugin and restarting the app (and allowing electron/youtube-music in firewall), it should theoretically connect to any device it finds - and play there the same music you play in the app

**Comment by playday3008** [comment] 2021-05-18 21:32
> if not, and you are using windows - I can build and upload binaries for you if needed

You can set up GitHub Actions or build it for me, bcoz im on Windows

**Comment by Araxeus** [comment] 2021-05-18 21:44
Here you go
https://drive.google.com/drive/folders/1Kfa4USQtoUjZTZLzgToDM6kMELdkRqgC?usp=sharing

**Comment by playday3008** [comment] 2021-05-18 21:57
Not working @Araxeus

**Comment by Araxeus** [comment] 2021-05-18 22:21
I have uploaded a new version, the first button in 'Plugins' menu should be now 'Update Chromecast List'
can you download again and try it?

I also included message box with current status

**Comment by playday3008** [comment] 2021-05-18 22:54
Well, device found
![image](https://user-images.githubusercontent.com/18056374/118733431-868f0300-b83c-11eb-80b1-ceb322445d2f.png)
But search output incorrect
![image](https://user-images.githubusercontent.com/18056374/118733484-a1617780-b83c-11eb-97fe-2c5f3e8dfb3f.png)

P.S. Maybe you have Telegram to contact?

**Comment by Araxeus** [comment] 2021-05-18 23:16
I've fixed that, you can download from [folder ](drive.google.com/drive/folders/1Kfa4USQtoUjZTZLzgToDM6kMELdkRqgC?usp=sharing) again 😝

Did it only find the device after clicking the Update button in the menu? or did it find it before?
Does it say anything when playing songs / pausing songs?

> Telegram Username [@Oksidoxi](https://t.me/Oksidoxi)

**Comment by BelgarionNL** [comment] 2021-06-23 14:39
so how do you cast. I have the latest version in windows and I dont see the plugin.

**Comment by Araxeus** [comment] 2021-06-23 19:56
@BelgarionNL it hasn't been released yet (there is an open pull request)

Love your username BTW, is it from the Belgariad/Malloreon or just random? :P

**Comment by BelgarionNL** [comment] 2021-06-25 00:40
yea its from the belgariad ofcourse :)

**Comment by kultawat** [comment] 2021-07-18 03:31
How can I test this on mac?

**Comment by Beersteddy** [comment] 2021-11-22 23:58
@Araxeus 
Hi
Is there any update on cast functionality?

I can se cast icon on latest 1.14.0 but clicking it really does completely nothing.
![image](https://user-images.githubusercontent.com/91010735/142952511-37e7bccb-b410-4a97-aab5-2f0d2bc994fb.png)


Tried 1.12.1 from your gdrive but I don't see in there any option to cast at all

**Comment by cmcinroy** [comment] 2021-12-07 16:30
@Beersteddy I just noticed the same icon. Turns out it's from the underlying Youtube Music service. Presumably, the reason it does nothing in this app is that in a browser it brings up the menu to select the target cast device.

It would be interesting to know whether this new feature in the base service gets us any closer to casting from an electron app.

**Comment by Araxeus** [comment] 2021-12-07 16:33
> It would be interesting to know whether this new feature in the base service gets us any closer to casting from an electron app.

No it sadly doesn't, their internal implementation doesn't work because electron doesn't support[[1](https://github.com/electron/electron/issues/869)][[2](https://github.com/electron/electron/issues/7024)] the `chrome.cast` api)

#509 will remove this button since it doesn't work. but PR #296 could be re-opened in the future (it mostly works)

**Comment by Araxeus** [comment] 2021-12-07 16:35
@Beersteddy 
> Tried 1.12.1 from your gdrive but I don't see in there any option to cast at all

Thats because you would need to clone the [branch](https://github.com/Araxeus/youtube-music/tree/chromecast) to test the latest changes (gdrive was a very early alpha version)

**Comment by JellyBrick** [comment] 2023-10-07 09:19
Duplicate of #113

**Closed by JellyBrick** 2023-10-07 09:19 UTC
Labels: enhancement
