### ISSUE TITLE
Discord Rich Presence doesn't auto update

### ISSUE THREAD

**Issue by AdamPype** [th-ch/youtube-music#504] opened 2021-12-01 13:30 UTC
For some reason, the Discord Rich Presence gets stuck on whatever song it was playing before when it starts playing a new song. If I manually press the next song button on Youtube Music or select a song then it updates, otherwise, it doesn't.

Any ideas about what might be causing this?

For example:
![image](https://user-images.githubusercontent.com/43540805/144242934-8f3f0200-8765-4a57-8e16-01e747e774a1.png)
![image](https://user-images.githubusercontent.com/43540805/144243028-4744ecd9-d9dd-4e37-baf9-ac3dd94cfb40.png)

**Comment by Araxeus** [comment] 2021-12-01 17:10
#477 should have fixed this

New app version including said fix will be released in the near future ^_^

**Comment by AdamPype** [comment] 2021-12-01 23:09
yay! that's great news! thank you so much for the reply!

**Comment by DereC4** [comment] 2021-12-03 23:50
thx

**Comment by NuclearMeltdown** [comment] 2021-12-21 08:14
Will this also fix notifications not showing up and the tuna plugin not updating unless songs are skipped, or is that a different issue?

**Comment by Araxeus** [comment] 2021-12-21 15:37
> Will this also fix notifications not showing up and the tuna plugin not updating unless songs are skipped, or is that a different issue?

that was already fixed in earlier PR's.
Now just waiting for a new version to be released that includes those latest changes

**Comment by mesmerx** [comment] 2021-12-22 17:57
the fix should be in the lastest release :)

**Comment by Araxeus** [comment] 2021-12-22 17:59
> the fix should be in the lastest release :)

no its not. new version wasn't released unless you wrote this in the future? O_o

**Comment by NuclearMeltdown** [comment] 2021-12-23 05:50
@Araxeus I built the app from source and the main issues do seem to be fixed. The only thing I noticed is that the 'time left' value in the Discord rich presence doesn't update properly. When the next song in an album or playlist starts, the counter is always off from what it should be. For example, when the next song starts and it's 4 minutes long, right after starting, the rich presence shows a minute left, or just 0:00. If it's stuck at 0:00, it mostly won't go back up at all when a new song starts. It works fine when manually starting or skipping a song. In some rarer cases, the counter doesn't react to skipping forwards or backwards in a song or pausing at all, just song change events. In this case, the counter is stuck counting down from whatever value it had from the start of the song. Though I haven't found a way to reproduce it yet, it's fixed by restarting the app. I know that what I tested isn't an official release, but I just wanted to give a heads up that in the current state of the code, not everything is fixed, even though it's a rather minor issue.

**Comment by Araxeus** [comment] 2021-12-23 09:59
@NuclearMeltdown thank you for the details, much appreciated

Sadly i've already encountered this bug but honestly have no idea whats causing it
(I *think* it might be a bug with the discord library since from my testing, the time value that we pass to discord is correct)

**Comment by NuclearMeltdown** [comment] 2021-12-23 11:37
Yeah, I just noticed that it works perfectly fine in that other, for some reason more popular YTM wrapper. But I refuse to use it because it uses so many more resources for the same or even less functionality.

**Comment by mesmerx** [comment] 2021-12-23 14:46
> > the fix should be in the lastest release :)
> 
> no its not. new version wasn't released yet... unless you wrote this in the future? O_o
> 
> (#477 was merged on Nov 30, 2021 and last version was released in Nov 09, 2021)

oh sorry i loses myself a little with releases

**Comment by Araxeus** [comment] 2022-01-03 16:16
https://github.com/th-ch/youtube-music/releases/tag/v1.15.0 includes a fix for this

**Closed** 2023-10-07 07:03 UTC
Labels: fix-available
