### ISSUE TITLE
Add "Connect to a device" button

### ISSUE THREAD

**Issue by lucashsbifsc** [th-ch/youtube-music#1220] opened 2023-08-11 19:59 UTC
I want to share my musics of notebook on the TV.

![image](https://github.com/th-ch/youtube-music/assets/124683425/67cac953-f0c1-48be-8b5f-47d6abe03f1b)

**Comment by JellyBrick** [comment] 2023-10-07 09:19
Duplicate of #113

**Closed by JellyBrick** 2023-10-07 09:19 UTC
