### ISSUE TITLE
[Bug]: 'Synced Lyrics' doesn't work with 'Adblocker' enabled (Blocker = 'In player')

### ISSUE THREAD

**Issue by Irgendeinwer** [th-ch/youtube-music#2367] opened 2024-08-25 22:13 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

NixOS 24.11.20240821.c374d94 (Vicuna) x86_64

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable 'Synced Lyrics' plugin
2. Enable 'Adblocker' plugin
3. Set 'Blocker' option of the 'Adblock' plugin to "In player"
4. Open the 'LYRICS'-tab

### Expected Behavior

The Lyrics should be shown.

### Actual Behavior

Error: "⚠️ - No lyrics found for this song."

### Enabled plugins

1. Synced Lyrics
2. Adblocker

### Additional Information

This error occurs on every song. I disabled every plugin except the 2 mentioned and cleared the app cache.

**Comment by JellyBrick** [comment] 2024-08-28 03:18
Duplicate of #2310

**Closed by JellyBrick** 2024-08-28 03:18 UTC
