### ISSUE TITLE
[Feature Request] WebNowPlaying integration with Rainmeter

### ISSUE THREAD

**Issue by dethknite** [th-ch/youtube-music#648] opened 2022-03-16 13:53 UTC
This functionality is already implemented in the ytmdesktop electron app.
https://github.com/ytmdesktop/ytmdesktop/blob/master/src/providers/rainmeterNowPlaying.js

**Comment by SixSiege** [comment] 2022-04-20 15:33
yes please

**Comment by JellyBrick** [comment] 2023-10-07 07:20
Duplicate of #329

**Closed by JellyBrick** 2023-10-07 07:20 UTC
Labels: duplicate
