### ISSUE TITLE
[Bug]: Syntax Error when downloading

### ISSUE THREAD

**Issue by MiekoHikari** [th-ch/youtube-music#2208] opened 2024-07-09 16:45 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 11 Home Version	23H2 Installed on	‎6/‎28/‎2024 OS build	22631.3737 Experience	Windows Feature Experience Pack 1000.22700.1009.0

### What CPU architecture are you using?

x64

### Reproduction steps

(assuming fresh install)
1. Enable the downloader plugin
2. Login with Google
3. Change download directory
4. Works for a while, after listening to multiple songs you will get an error pop up

### Expected Behavior

The song to download

### Actual Behavior

![image](https://github.com/th-ch/youtube-music/assets/77004524/0127d38f-eefa-4647-b134-efb7c555ca34)
Syntax Error in all songs

### Enabled plugins

1. Discord Rich Presence
2. Ad blocker (also doesn't work)
3. In-App Menu
4. Navigation

### Additional Information

It works after I delete all user data in %appdata% but the issue appears again after a while

**Comment by TecnikOfficial** [comment] 2024-07-09 17:57
experiencing same issue

**Comment by 4096Richard** [comment] 2024-07-09 20:44
I do Have this issue too it just happened today even though i have had this for half a year already and never had this issue 
has anybody figured out anything because deleting the app data doesn't work right now

**Comment by 4096Richard** [comment] 2024-07-10 00:10
Another note i wanted to mention i decided to keep rolling back version to see if it was something new but i went all the way back to 2.0.1 and still had that same error 
something to note while on the version 3.0.0 it didn't give me the syntax error instead a # name error thing 
just something to note

**Comment by DrWafflePhD** [comment] 2024-07-10 00:43
Same thing, playlists don't work either

**Comment by Aleuso** [comment] 2024-07-10 02:42
same issue here too

**Comment by MiekoHikari** [comment] 2024-07-10 04:56
After inspecting the source code and playing with it for a while, I've found that:

This issue seems to be related to a dependency of the YT-MUSIC app (Youtubei.js)
[Issue#683 in LaunRT/YouTube.js](https://github.com/LuanRT/YouTube.js/issues/683)

Downgrading the package doesn't seem to work.

**Comment by JellyBrick** [comment] 2024-07-10 09:19
This issue was caused by a breaking change in the YouTube internal API. 

See https://github.com/LuanRT/YouTube.js/issues/683

**Comment by JsThiago** [comment] 2024-07-11 17:44
Same thing unfortunately

**Comment by JellyBrick** [comment] 2024-07-12 00:33
Please do not comment "same here" (this will send a spam notification to everyone who is participating in the issue), instead hit the 👍 button.

**Comment by MiekoHikari** [comment] 2024-07-13 07:04
Commit: [0415745](https://github.com/th-ch/youtube-music/commit/041574570f3d617ed69b55981574590cad087afb)
Issue: #2218 

The new package version of Youtubei.js fixed this issue; I've tested it on my own machine and it passed all tests like normal.

**Comment by JellyBrick** [comment] 2024-07-14 10:31
fixed by #2218

**Closed by JellyBrick** 2024-07-14 10:31 UTC
Labels: bug, dependencies
