### ISSUE TITLE
[Bug]: In-app menu make history page very lag

### ISSUE THREAD

**Issue by TN-TechNoob** [th-ch/youtube-music#2322] opened 2024-08-02 20:23 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable In-app menu plugin
2. Click account
3. Go to History

### Expected Behavior

It should be smooth like web Youtube music

### Actual Behavior

Horible performance

### Enabled plugins

![image](https://github.com/user-attachments/assets/e01a53ac-1aae-4286-92b4-db9323b3c507)

### Additional Information

CPU: AMD R9 7900X
GPU: AMD RX 6600XT
All the driver are latest

**Comment by JellyBrick** [comment] 2024-08-04 06:24
Duplicate of #2266

**Closed by JellyBrick** 2024-08-04 06:24 UTC
