### ISSUE TITLE
[Bug]: Ad blocking doesn't work

### ISSUE THREAD

**Issue by G-0din** [th-ch/youtube-music#1959] opened 2024-04-10 18:03 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.5

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

1909

### What CPU architecture are you using?

x64

### Reproduction steps

turn on ad blocker

### Expected Behavior

block ads

### Actual Behavior

ads keep showing up even with the plugin active

### Enabled plugins

ad blocker

**Comment by Trixarian** [comment] 2024-04-10 21:27
Toggle with blocklists under Blocker in the ad blocker Plugin. Go to Options---> Advanced options---> Edit config.json and change:
``			"additionalBlockLists": [],``
to
`` 			"additionalBlockLists": [
				"https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt",
				"https://filters.adtidy.org/extension/ublock/filters/122_optimized.txt"
			],``
and restart the app
That solves the ads issue for me

**Comment by JellyBrick** [comment] 2024-04-11 09:08
## PLEASE READ THE **`Preflight Checklist`**
![image](https://github.com/th-ch/youtube-music/assets/16558115/f2305527-14ce-4917-b8d6-ada171314d09)
![image](https://github.com/th-ch/youtube-music/assets/16558115/5d78aa0d-e606-4762-b5b4-731706f4cbf2)


Duplicate of #1817

**Closed by JellyBrick** 2024-04-11 09:08 UTC
Labels: duplicate
