### ISSUE TITLE
[Bug]: No menu bar on Windows 11

### ISSUE THREAD

**Issue by cdsoftw** [th-ch/youtube-music#2419] opened 2024-09-16 21:10 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.0, 3.5.1, 3.5.2, 3.4.X, 3.3.X

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Reproduction steps

1. Be on Windows 11
2. Uninstall, if necessary
3. Perform a fresh install
4. Observe that there is no menu bar

### Expected Behavior

Menu bar is visible and accessible on Windows 11

### Actual Behavior

There is no menu bar, and pressing alt or ` does not make it appear. Without a menu bar, there is essentially no plugin functionality, and no settings can be changed in the UI.

### Enabled plugins

N/A, fresh install

### Additional Information

I have attempted fresh installs of more than 5 versions going back to the latest 3.3, both portable and not, and they all have this issue. It appears to me that there is essentially no Windows 11 support whatsoever due to this critical, show-stopping bug.

**Comment by cdsoftw** [comment] 2024-09-16 21:17
Related to [this issue](https://github.com/th-ch/youtube-music/issues/2339), but this seems to have a much wider scope than documented there, so I created this one.

**Comment by ArjixWasTaken** [comment] 2024-09-16 23:26
Windows 11 support should be fine.
I don't think the issue is related to windows 11 itself.

I myself am running windows 11 (albeit a buggy insider release that cannot be updated) and I didn't have such issues.

Your frustration (from the other issue) is understandable.

I can't be active during September due to uni exams.

If nobody else gives this a look, I guarantee that once September is over I'll do my best to fix this.

**Comment by JellyBrick** [comment] 2024-09-17 06:31
I'm using Windows 11, and it works on my machine.
can't reproducible.

**Comment by JellyBrick** [comment] 2024-09-17 06:34
> Related to [this issue](https://github.com/th-ch/youtube-music/issues/2339), but this seems to have a much wider scope than documented there, so I created this one.

And, if you are experiencing the same issue, please comment on that issue.

**Comment by JellyBrick** [comment] 2024-09-17 06:34
Duplicate of #2339

**Closed by JellyBrick** 2024-09-17 06:34 UTC
