### ISSUE TITLE
[Bug]: crash when launching on linux

### ISSUE THREAD

**Issue by JaeAeich** [th-ch/youtube-music#2287] opened 2024-07-29 03:21 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.4.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Ubuntu

### Operating System Version

24.04

### What CPU architecture are you using?

x64

### Reproduction steps

1. Start Youtube music

### Expected Behavior

IT should start!

### Actual Behavior

It doesn't launch is done via desktop icon, and when done throw CLI, if get the below error.
```
❯ youtube-music --version
LaunchProcess: failed to execvp:
/opt/YouTube
[6243:0729/084906.122984:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
zsh: trace trap (core dumped)  youtube-music --version
```

### Enabled plugins

Its a fresh install.

**Comment by busyboxx** [comment] 2024-07-29 03:41
I was facing the same issue for latest version of YT music in Ubuntu, this workaround worked for me
by running from terminal and with --no-sandbox option 
`youtube-music --no-sandbox`

**Comment by JellyBrick** [comment] 2024-07-29 07:48
Duplicate of #2007

**Closed by JellyBrick** 2024-07-29 07:48 UTC
