### ISSUE TITLE
[Feature Request] REST API for the application

### ISSUE THREAD

**Issue by Zo-Bro-23** [th-ch/youtube-music#653] opened 2022-03-21 11:23 UTC
Hi,
It would be great if there was a plugin to enable a REST API for the application. I, personally, would like to control the application with my voice (similar to Google Assistant), and since it would be tedious to build this into the application, I don't mind writing my own code for it. However, there is no clear API for the application, so it would be awesome if you could build a REST API into the application itself.

Thanks!

**Comment by Araxeus** [comment] 2022-03-21 16:30
What commands would you like?

could maybe use https://www.electronjs.org/docs/latest/api/protocol

**Comment by Zo-Bro-23** [comment] 2022-03-22 01:50
I would like ```song-info``` and ```song-control```. Both of these are available as ```providers```, but it would be great if it could be made as a REST API. I am a bit busy now, but I will try it out when I'm free and perhaps send a pull request.

**Comment by dgalli1** [comment] 2022-04-18 16:51
Not aware how windows works in this case.
But stuff like this should be controllable via MPRIS on Linux. (So  you wouldn't really need a new api.)  I guess Windows got something similar.
https://wiki.archlinux.org/title/MPRIS

On linux you can  sniff the  media info via dbus-monitor. And also send commands.

For example with this  you could listen to the current song:
dbus-monitor interface="org.mpris.MediaPlayer2.Player"

**Comment by SHU-red** [comment] 2022-12-09 12:58
Im using a window manager (sway) on linux, which already provides the "standard" everybody uses to control the media-player via custom bar etc.

I think its [dbus = mpris = mpd] right?
Don't know much about it but im using the *awesome* `th-ch/youtube-music` since a long time now but i think its not possible to connect this stuff?

I already installed mpd on my fedora setup via
https://fedoramagazine.org/playing-music-on-your-fedora-terminal-with-mpd-and-ncmpcpp/

But waybar player shows me constantly "stopped"

**Comment by dgalli1** [comment] 2022-12-09 14:54
Yeah this is probably related to this issue:
https://github.com/th-ch/youtube-music/issues/872

**Comment by Araxeus** [comment] 2023-01-08 07:57
#946 adds a protocol which can be be called like so:
```
youtubemusic://pause
```
Currently only supports song-controls and has no response

Protocol with response can be registered for song-info later down the road

**Comment by Zo-Bro-23** [comment] 2023-01-08 08:54
> #946 adds a protocol which can be be called like so:
> 
> ```
> youtubemusic://pause
> ```
> 
> Currently only supports song-controls and has no response
> 
> Protocol with response can be registered for song-info later down the road

Cool!

**Comment by Zo-Bro-23** [comment] 2023-03-31 02:46
Will be fixed by #1094.

**Comment by amplexus** [comment] 2023-04-16 07:24
The command-line `playerctl` app can control it using the existing D-BUS MPRIS interface / protocol that youtube-music supports.  For example:

`playerctl --player=youtube-music pause`

and 

`playerctl --player=youtube-music play`

**Comment by JellyBrick** [comment] 2023-10-07 09:25
Duplicate of #739

**Closed by JellyBrick** 2023-10-07 09:25 UTC
Labels: duplicate
