### ISSUE TITLE
[Feature Request] Plugin for Rainmeter integration using WebNowPlaying

### ISSUE THREAD

**Issue by johnrijoy** [th-ch/youtube-music#738] opened 2022-06-05 05:21 UTC
I think it would be great if you add this feature in next versions.
WebNowPlaying is used by using a BrowserExtension, and it has been implemented in a [similar youtube music desktop application](https://github.com/ytmdesktop/ytmdesktop) developed on electron, so I think it will be useful if you could add it.
Thank you
links:
https://github.com/tjhrulz/WebNowPlaying
https://github.com/tjhrulz/WebNowPlaying-BrowserExtension
https://github.com/khanhas/spicetify-cli/blob/master/Extensions/webnowplaying.js
https://github.com/ytmdesktop/ytmdesktop/blob/master/src/providers/rainmeterNowPlaying.js

**Comment by johnrijoy** [comment] 2022-06-05 05:24
I am completely new to electron app development and also to creating plugins for this application. But if given some pointers, I would very much like to develop the plugin myself.

**Comment by JellyBrick** [comment] 2023-10-07 07:20
Duplicate of #329

**Closed by JellyBrick** 2023-10-07 07:20 UTC
