### ISSUE TITLE
[Bug]: Cannot change plugins/view options menu as the button for it is missing.

### ISSUE THREAD

**Issue by Cloudlift2d** [th-ch/youtube-music#2163] opened 2024-06-16 13:23 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.2

### Reproduction steps

1) Open Youtube Music Desktop App.
2) Observe absence of Options button in the top left. File, edit, view and the rest are still there.

### Expected Behavior

I expect the option called "Options" to be there.
![image](https://github.com/th-ch/youtube-music/assets/101243773/1b825abb-064c-4008-ab9a-391d82045abd)

### Actual Behavior

There is no button called "Options" there.

### Enabled plugins

Not sure as I cannot see the list as this issue is about  the button to find that list being missing.

### Additional Information

I used version 3.3.2 until it randomly stopped opening one day. Then, I updated to the latest, 3.3.12, where I had playback issues that conform to other's issues with the "Crossplay" plugin. It took me a while to realise this, and I only came to that conclusion after downgrading to 3.3.10. In my attempt to fix this issues by turning off the plugin, I noticed that I could not due to the absence of the button called "Options".
![image](https://github.com/th-ch/youtube-music/assets/101243773/ed852b94-c387-48c6-a473-f519e361a190)

**Comment by JellyBrick** [comment] 2024-06-29 00:49
Duplicate of #2113

**Closed by JellyBrick** 2024-06-29 00:49 UTC
