### ISSUE TITLE
[Bug]: Macos top left small bar glitch

### ISSUE THREAD

**Issue by Sytten** [th-ch/youtube-music#1617] opened 2024-01-09 22:10 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

macOS

### Operating System Version

MacOS 14.2

### What arch are you using?

arm64 (including Apple Silicon)

### Reproduction steps

<img width="295" alt="Screenshot 2024-01-09 at 5 07 39 PM" src="https://github.com/th-ch/youtube-music/assets/2366731/8a6272bc-5b5f-4eec-8782-b5dafd9f27fb">

### Expected Behavior

No weird menu icon that can be clicked

### Actual Behavior

Weird menu icon

### Enabled plugins

None

**Comment by luluna02** [comment] 2024-01-27 11:58
Hello, I also have a mac and I noticed the same thing. The problem is for macOS only as the condition is supposed to exclude macOS when appending logo to title ( as show in the following screenshot) but still called it again so the condition had no more effect. I removed the line and it works perfectly. Can I commit the change? 

<img width="1105" alt="Screenshot 2024-01-27 at 12 53 56 PM" src="https://github.com/th-ch/youtube-music/assets/133816965/b20b84bc-534c-47ce-925e-ac7f9c3b8c2c">

**Comment by luluna02** [comment] 2024-01-27 13:42
Hello @JellyBrick, @Sytten I fixed this issue. Can I commit the change and become a contributor? ( it would be very helpful as part of a university course, thanks!) :) 

![Uploading Screenshot 2024-01-27 at 2.42.18 PM.png…]()

**Comment by luluna02** [comment] 2024-01-27 13:45
Hello @JellyBrick, @Sytten I fixed this issue. Can I commit the change and become a contributor? ( it would be very helpful as part of a university course, thanks!) :)

![Uploading Screenshot 2024-01-27 at 2.43.01 PM.png…]()

**Comment by inson1** [comment] 2024-01-27 14:43
@luluna02 then please create pr (pull request) for it and btw your image didnt upload

**Comment by luluna02** [comment] 2024-01-27 15:33
![Uploading Screenshot 2024-01-27 at 2.43.01 PM.png…]()

**Comment by luluna02** [comment] 2024-01-27 15:35
![Uploading Screenshot 2024-01-27 at 2.43.01 PM.png…]()

**Comment by luluna02** [comment] 2024-01-28 19:22
@JellyBrick May you close this issue?

**Comment by inson1** [comment] 2024-01-28 20:21
@luluna02 https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by luluna02** [comment] 2024-01-29 09:27
@inson1 Thank you for the help :) done.

**Closed** 2024-01-29 12:50 UTC
Labels: bug
