### ISSUE TITLE
[Bug]: Ads started playing

### ISSUE THREAD

**Issue by HyperionTR** [th-ch/youtube-music#1955] opened 2024-04-09 16:54 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.5.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro ver. 22H2 comp. 19045.4170

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.3.5.0

### Reproduction steps

0. Have the "Ad blocker" plugin enabled with the blocker set to "In player"
1. Start playing any song.
2. Click the "play icon" in other recomended songs of the "next" section or keep on listening 'till the songs finish by themselves.
3. An ad may play inbetween songs.

### Expected Behavior

The songs playback is uninterrupted by ads.

### Actual Behavior

Ads play inbetween songs despite the Ad Blocker plugin being enabled.

### Enabled plugins

1. Ad blocker
2. Ambiend Mode
3. Discord Rich Presence
4. Downloader
5. Exponential volume
6. In-App menu
7. Navigation
8. Precise volume
9. Taskbar Media Control
10. Video quality Changer
11. Green color theme.

### Additional Information

The ads started playing as of April 8 2024, approximatedly between 8pm - 12am UTC+8 (Mexico) time.
Before that time on the same day, no ads were interrupting the playback.

**Comment by senolfndk** [comment] 2024-04-10 01:34
same problem

**Comment by th30nly** [comment] 2024-04-10 02:38
Confirmed on MacOS Monterey.
Youtube Version 3.3.5

**Comment by badjavadev12** [comment] 2024-04-10 06:55
Same problem on arch

**Comment by kasem545** [comment] 2024-04-10 07:16
same on windows 10

**Comment by CreativeRoy** [comment] 2024-04-10 09:28
Same problem on arch

**Comment by senolfndk** [comment] 2024-04-10 10:03
👍🤗

Uploading Kayıt 2024-04-10 125752 - Trim.mp4…

**Comment by senolfndk** [comment] 2024-04-10 10:03
https://github.com/th-ch/youtube-music/assets/52818836/45be90e0-5390-40c0-a9aa-66e87fd40243

**Comment by senolfndk** [comment] 2024-04-10 10:06
👍🤗

https://github.com/th-ch/youtube-music/assets/52818836/0d1e139c-25b6-49f4-b972-1f8a8a542982

**Comment by HyperionTR** [comment] 2024-04-10 14:01
Does anyone has a quick fix for this?
Something like a new block list or something for the plugin to work in?

**Comment by HyperionTR** [comment] 2024-04-10 14:24
# Got a quick fix for this error!!!

Given that the plugin allows for custom and aditional Ad Block-lists, I tried looking up for, and downloading a new Youtube Ad-Blocklist and adding it to the `config.json` of Youtube Music.

## Download of the list

The list is maintained in a github repository, the file itself it's approx. 5MB.

[Github repo link](https://github.com/jerryn70/GoodbyeAds/blob/master/Extension/GoodbyeAds-YouTube-AdBlock.txt) || [Raw file link](https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt)

## Install process

0. Enable "Ad blocker" plugin
1. Set the blocker mode to "With blocklists"
![imagen](https://github.com/th-ch/youtube-music/assets/49888382/07998fe9-475e-44de-b182-189cf862eee7)
2. Download the blocklist file where you can find it later in your computer
![imagen](https://github.com/th-ch/youtube-music/assets/49888382/b14fad05-5b4b-42af-9354-44354c0cfd07)
3. In the Youtube Music menu, follow the path `Options → Advanced Options → Edit `config.json``
![imagen](https://github.com/th-ch/youtube-music/assets/49888382/bc5845c6-6adb-49e2-ba4a-35506b025e16)
4. In the config file, scroll down until you find the "adblocker" category and add the **absolute path** of the file you just downloaded on your computer inside the brackets of "additionalBlockLists". ***DON'T FORGET TO ESCAPE TWICE EACH BACKSLASH***.
![imagen](https://github.com/th-ch/youtube-music/assets/49888382/8987a813-0ca7-4a30-b3b2-d693b6086c80)
5. ***RESTART THE APP***, Haven't tried with a simple reload, but the restart should be way better anyway and *that's it!*. No more ads are played anytime when listening music :3

**Comment by JellyBrick** [comment] 2024-04-10 15:46
## Please, read the `Preflight Checklist` before writing issues.

![image](https://github.com/th-ch/youtube-music/assets/16558115/6911238d-8dda-4b88-8491-f60147acbde1)


Duplicate of #1817

**Closed by JellyBrick** 2024-04-10 15:46 UTC

**Comment by jonatasferreirajk** [comment] 2024-05-16 23:21
> # Got a quick fix for this error!!!
> Given that the plugin allows for custom and aditional Ad Block-lists, I tried looking up for, and downloading a new Youtube Ad-Blocklist and adding it to the `config.json` of Youtube Music.
> 
> ## Download of the list
> The list is maintained in a github repository, the file itself it's approx. 5MB.
> 
> [Github repo link](https://github.com/jerryn70/GoodbyeAds/blob/master/Extension/GoodbyeAds-YouTube-AdBlock.txt) || [Raw file link](https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt)
> 
> ## Install process
> 0. Enable "Ad blocker" plugin
> 1. Set the blocker mode to "With blocklists"
>    ![imagen](https://private-user-images.githubusercontent.com/49888382/321271823-07998fe9-475e-44de-b182-189cf862eee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MDE1NDgsIm5iZiI6MTcxNTkwMTI0OCwicGF0aCI6Ii80OTg4ODM4Mi8zMjEyNzE4MjMtMDc5OThmZTktNDc1ZS00NGRlLWIxODItMTg5Y2Y4NjJlZWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDIzMTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMDM2YzM3MWY3NGVjOGE1ZDE1MWI2YzM2Y2Y4MjU0ZDE0M2Y0NjJjZTBkMjQzOGYzMzI2NDMyMWRlMTg4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._QKDtr5ECpz8TslXOwqf7uLJQ-ryF-91VnJhfmio9Gs)
> 2. Download the blocklist file where you can find it later in your computer
>    ![imagen](https://private-user-images.githubusercontent.com/49888382/321272160-b14fad05-5b4b-42af-9354-44354c0cfd07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MDE1NDgsIm5iZiI6MTcxNTkwMTI0OCwicGF0aCI6Ii80OTg4ODM4Mi8zMjEyNzIxNjAtYjE0ZmFkMDUtNWI0Yi00MmFmLTkzNTQtNDQzNTRjMGNmZDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDIzMTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNmNlNGJjZmNlZDRlMGU2MzkwYTY4NjYwMWI4NWRlODRmYWQwZWIxZGY2OWNhYmIwNDgyMzlhZWVhNTVlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t1qT158Pu7psqPx929UrruBAqpsmEGFfhlJn3K2fNIc)
> 3. In the Youtube Music menu, follow the path `Options ⇒ Advanced Options ⇒ Edit config.json`
>    ![imagen](https://private-user-images.githubusercontent.com/49888382/321273262-bc5845c6-6adb-49e2-ba4a-35506b025e16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MDE1NDgsIm5iZiI6MTcxNTkwMTI0OCwicGF0aCI6Ii80OTg4ODM4Mi8zMjEyNzMyNjItYmM1ODQ1YzYtNmFkYi00OWUyLWJhNGEtMzU1MDZiMDI1ZTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDIzMTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YzY4ODlkOTMyOTI0ZGJjNGU1Y2ExMDc1NWY0MjEyYTA2NzhiYzZlZmY4ODExMjcxMjQ0YjliMDVkNzg0M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mjqfbkgd_LXRTg-W8T87caWuawHPjonV6XTDdqj_Vps)
> 4. In the config file, scroll down until you find the "adblocker" category and add the **absolute path** of the file you just downloaded on your computer inside the brackets of "additionalBlockLists". _**DON'T FORGET TO ESCAPE TWICE EACH BACKSLASH**_.
>    ![imagen](https://private-user-images.githubusercontent.com/49888382/321274835-8987a813-0ca7-4a30-b3b2-d693b6086c80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MDE1NDgsIm5iZiI6MTcxNTkwMTI0OCwicGF0aCI6Ii80OTg4ODM4Mi8zMjEyNzQ4MzUtODk4N2E4MTMtMGNhNy00YTMwLWIzYjItZDY5M2I2MDg2YzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDIzMTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZTcwYjljOTc4MDBlZDk5ZTg0NmY4YmUzMjU1MGZjYmZiMjNjNjhkZWM1ZjZkYTQ2N2Y5NzlkNzYxMjk3MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.18vzkfow6GaAAkGlkmEYFHalb5e0uqMaKfEZcgj-ueg)
> 5. _**RESTART THE APP**_, Haven't tried with a simple reload, but the restart should be way better anyway and _that's it!_. No more ads are played anytime when listening music :3

This Works here!!! Tranks 👍🏽
