### ISSUE TITLE
[Bug]: Laggy UI on Windows 11

### ISSUE THREAD

**Issue by ioshomebrew** [th-ch/youtube-music#2194] opened 2024-06-30 03:19 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

Opened app, and while using app the UI is pretty laggy

### Expected Behavior

UI should be smooth

### Actual Behavior

UI is laggy when navigating playlists and songs

### Enabled plugins

Sponsor Block
Navigation
In app menu
Ad blocker

**Comment by Shadowphoenix** [comment] 2024-07-16 15:51
this seems to be a rather common issue that has been reported a bunch of times already.
This is essentially a duplicate of what i posted a few weeks back: #2155

**Comment by Smoltallk** [comment] 2024-07-18 11:17
This hasnt been fixed on the newest version either, loading big playlists still causes the app to lag (3.4.1 on linux mint, havent checked on windows 11 yet).

**Comment by Shadowphoenix** [comment] 2024-07-18 12:35
> This hasnt been fixed on the newest version either, loading big playlists still causes the app to lag (3.4.1 on linux mint, havent checked on windows 11 yet).

others mentioned disabling the In-App-Menu-Extension. For me that makes no difference but that helped at least two people.

**Comment by JellyBrick** [comment] 2024-07-28 06:09
Duplicate of #2266

**Closed** 2024-07-28 06:09 UTC
Labels: duplicate
