### ISSUE TITLE
[Bug]: Album Actions don't work

### ISSUE THREAD

**Issue by Brawnstorm** [th-ch/youtube-music#2502] opened 2024-10-14 15:33 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.1.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.4.1.0

### Reproduction steps

1. Activate "Album Actions" plugin

2. Select an Album

3. Click on any of the Album Actions

![Screenshot_5](https://github.com/user-attachments/assets/923438e7-1fe7-447d-b034-5c6900837298)

### Expected Behavior

It would Like/Dislike every song in the Album

### Actual Behavior

Does Nothing

### Enabled plugins

API Server Beta, Discord Rich Server, Exponential Volume, Shortcut, Navigation, Notification, Picture-In-Picture, and Precise Volume

### Additional Information

I tried it without every Plugin activated except Album Actions and it didn't work.

**Comment by jackdevlamond** [comment] 2024-10-28 18:48
Not working for me either

**Comment by JellyBrick** [comment] 2024-12-06 03:09
Duplicate of #2312

**Closed by JellyBrick** 2024-12-06 03:09 UTC
Labels: bug
