### ISSUE TITLE
[Bug]: ads still playing

### ISSUE THREAD

**Issue by RandomNewUser2022** [th-ch/youtube-music#1952] opened 2024-04-09 12:07 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.5.0

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

windows 11

### What CPU architecture are you using?

x64

### Reproduction steps

ads still play when i use this application

### Expected Behavior

no ads playing

### Actual Behavior

ads still play when i use this application

### Enabled plugins

default

### Additional Information

![image](https://github.com/th-ch/youtube-music/assets/150843245/9c44857b-371b-4e73-b423-8fa31b45bcb4)

**Comment by mrengy** [comment] 2024-04-09 14:52
I'm also experiencing this. I had experienced it today on an older version of the Mac OS app and just upgraded to 3.3.5 and am still experiencing it. Toggled off and on the ad blocker plugin, quit and restarted the app, and it's still happening.

Mac OS 14.3

Apple M3

**Comment by Ytrewqfdsacxz** [comment] 2024-04-09 16:28
same here
windows 11

**Comment by HyperionTR** [comment] 2024-04-09 16:57
Wow, haha, looks like someone just updated the Adblocker version used, 1 hour ago from this comment's writing.

So now we just wait a couple more hours before a new compilation is up that updated that dependancy.

**Comment by JellyBrick** [comment] 2024-04-10 15:45
Please, read the `Preflight Checklist` before writing issues.

Duplicate of #1817

**Closed by JellyBrick** 2024-04-10 15:45 UTC
