### ISSUE TITLE
[Feature Request]: Adding Rainmeter Integration

### ISSUE THREAD

**Issue by FearedFusionX** [th-ch/youtube-music#2321] opened 2024-08-02 18:55 UTC
Is it possible you can add rain meter interrogation so certain playing info widgets show the currently playing song?

**Comment by JellyBrick** [comment] 2024-08-02 22:29
Already has.

**Comment by JellyBrick** [comment] 2024-08-02 22:30
Duplicate of 329

**Closed by JellyBrick** 2024-08-02 22:29 UTC
Labels: invalid, question
