### ISSUE TITLE
[Feature Request]: Chrome cast?

### ISSUE THREAD

**Issue by CarmeloCampos** [th-ch/youtube-music#1820] opened 2024-03-02 22:01 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When I try to find the button to send audio to another compatible device, I can't find the button. 

### Proposed Solution

Enable the chrome cast plugin to be able to send audio / video to another device.

### Alternatives Considered

The navigator even has the option.
![image](https://github.com/th-ch/youtube-music/assets/31357533/50f9df3f-6f76-4661-82eb-c410e5d3fa73)

**Comment by inson1** [comment] 2024-03-02 22:23
@CarmeloCampos duplicate of https://github.com/th-ch/youtube-music/issues/113

**Comment by JellyBrick** [comment] 2024-03-03 09:25
Duplicated of #113

![image](https://github.com/th-ch/youtube-music/assets/16558115/2c7d160a-7dd8-46f5-8180-e667923d4320)
😅

**Closed by JellyBrick** 2024-03-03 09:25 UTC
