### ISSUE TITLE
[Feature Request] Add plugin to skip content warnings

### ISSUE THREAD

**Issue by Churchexe** [th-ch/youtube-music#1095] opened 2023-04-01 01:14 UTC
There are some songs which have content warnings when you pull them up, notable example being "Congratulations, You Survived Your Suicide" - Sycamore Smith - Grosspapa. As far as I can tell there is no way to skip this warning, so occasionally your playback will just completely stop because it landed on a song that had themes that daddy google doesn't think you're old enough to hear about yet. A plugin to automatically skip these sorts of warnings would be excellent. (can you tell I don't like google?)

**Comment by Araxeus** [comment] 2023-04-01 12:47
Clicking the "I understand" button is not a problem, implemented that in a few minutes

The problem is that clicking "I understand" seems to clear the queue for some reason...

![ytm-age-restrictions](https://user-images.githubusercontent.com/78568641/229289693-a91d802a-04e8-40b8-a514-f500471b8667.gif)

**Comment by th-ch** [comment] 2023-05-18 11:10
Closing because a solution is available!

**Closed by th-ch** 2023-05-18 11:10 UTC
