### ISSUE TITLE
[Feature Request]: android port 

### ISSUE THREAD

**Issue by Sensex00** [th-ch/youtube-music#2455] opened 2024-09-29 19:24 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to use this app on Android 

### Proposed Solution

Make a port on the android 

### Alternatives Considered

Firstly I have used app called vimusic but it was abandoned I tried several apps but like it's fork named rimusic I didn't like it it was not good 
Main thing is want ui to be close to youtube music with custom plug-in like this offers 

### Additional Information

I tried to use revanced but it just doesn't work without login and also I have to login with using seperate app microg 

With all seriousness If you would consider this app to port on Android it would be great

**Comment by Sensex00** [comment] 2024-09-29 19:30
Also I came across an app on iOS maybe you could take inspiration like on Android for ui custom plug-in settings tab maybe 

![235781207-6d1ad44e-0c32-4aec-9c75-cb928ca8a0d3](https://github.com/user-attachments/assets/e2e07c67-8735-49f3-9d8c-ffd46745cb59)

Sorry I don't think why I have shared this It would not be any help but anyway

**Comment by ArjixWasTaken** [comment] 2024-09-29 20:46
That would be a horrible app.
Please understand that we are merely wrapping the website https://music.youtube.com

That website would be shit for mobile.

**Comment by ArjixWasTaken** [comment] 2024-09-29 20:48
I recommend trying out echo.

https://github.com/brahmkshatriya/echo

**Comment by Sensex00** [comment] 2024-09-29 21:23
> That would be a horrible app. Please understand that we are merely wrapping the website https://music.youtube.com
> 
> That website would be shit for mobile.

I think you are right but what if the app made from Android ytm app not the website but I think this will be a lot of work to make such app maybe you are right but if the developers would will to make they can make similar app using 

https://github.com/zerodytrash/YouTube-Internal-Clients
App can be made but again it will be a lot of work for devs

**Comment by ArjixWasTaken** [comment] 2024-09-29 21:41
What you are asking for, is literally echo...

**Comment by Sensex00** [comment] 2024-09-29 21:43
> What you are asking for, is literally echo...

Ok man chill

**Comment by JellyBrick** [comment] 2024-09-29 22:32
Duplicate of #457

**Closed by JellyBrick** 2024-09-29 22:32 UTC
Labels: duplicate, wontfix

**Comment by ArjixWasTaken** [comment] 2024-09-30 13:39
> > What you are asking for, is literally echo...
> 
> Ok man chill

I was (and still am) chill
