### ISSUE TITLE
[Bug]: youtube music download error net:; Error_Failed

### ISSUE THREAD

**Issue by rahulsah18** [th-ch/youtube-music#2151] opened 2024-06-13 03:30 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Reproduction steps

![Screenshot 2024-06-13 083940](https://github.com/th-ch/youtube-music/assets/172564117/b4328f19-549c-4eef-8903-13fd0e01af25)

### Expected Behavior

Wants to problem to be solved as fast as possible

### Actual Behavior

error problem with youtube music download many songs doesnot download

### Enabled plugins

Adblocker Enabled
Downloader Enabled
In app menu Enabled
Navigation Enabled
SponsorBlock Enabled
Video Quality Changer Enabled

**Comment by JellyBrick** [comment] 2024-06-16 02:17
Duplicate of #1791

**Closed by JellyBrick** 2024-06-16 02:17 UTC

**Comment by rahulsah18** [comment] 2024-06-16 02:34
Can i know how can i solve it I didn’t understand the solution
