### ISSUE TITLE
[Bug]: Unable to download 

### ISSUE THREAD

**Issue by JeremyJoseMendezRomero** [th-ch/youtube-music#2746] opened 2024-12-20 13:46 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home - 22H2

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.6.2

### Reproduction steps

**First of all, thank you very much for your application, I love it so much.**

![YouTube_Music_cUUeSn9Ejr](https://github.com/user-attachments/assets/c86ff565-dfbd-4527-8380-28906c9fe176)

I am trying to download any song without success, I was able to download songs up to 10 days ago (approximately).

![explorer_KuosAQpUUH](https://github.com/user-attachments/assets/51d56add-0da2-4b67-8d25-3562be0dce93)

That song was the last one I was able to download on December 10

### Expected Behavior

Download the selected song as before

### Actual Behavior

When i hit the download button, i just receive this

![imagen](https://github.com/user-attachments/assets/eaa68e46-89d4-4eeb-8a61-06f24d2ef1c5)

Error: Unexpected token (1:71)

the rest of the plugins work perfectly, I also tried to deactivate all plugins except the Downloader without success, I get this warning every time.

### Enabled plugins

1. Ad blocker
2. Album actions
3. Ambient mode
4. Bypass age restictions
5. Downloader
6. Exponential volume
7. in-App menu
8. Lyrics genius
9. Notificacions
10. Precise volume
11. Skip disliked songs
12. Synced lyrics
13. Taskbar media controls
14. video quality changer
15. Video toggle

### Additional Information

As I wrote before, I try to deactivate all plugins except Downloader without success, changing all settings (Presets, quality, download on completion, changing the directory, logging out of my account).

Again, thanks a lot

**Comment by JellyBrick** [comment] 2024-12-20 14:42
Preflight Checklist?

Duplicate of https://github.com/th-ch/youtube-music/issues/2691, https://github.com/th-ch/youtube-music/issues/2628

**Closed by JellyBrick** 2024-12-20 14:42 UTC

**Comment by JeremyJoseMendezRomero** [comment] 2024-12-20 18:49
> Preflight Checklist?
> 
> Duplicate of #2691, #2628

I'm so sorry, I saw #2628 but it wasn't the same as mine and that's why I decided to open it, but I didn't really see #2691.
