### ISSUE TITLE
[Bug]: In-Player Ad-Blocker Not Working

### ISSUE THREAD

**Issue by SkyWolfXP** [th-ch/youtube-music#2029] opened 2024-05-05 07:53 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.6

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Reproduction steps

1. Select Ad-Blocker Type: In Player

### Expected Behavior

Block Ads

### Actual Behavior

Ads keep popping up

### Enabled plugins

- Ad-Blocker
- Bypass Age Restrictions
- Navigation
- Lyrics Genius
- Skip Disliked Songs
- Video Toggle
  - Mode: Disabled
  - Force Remove Tab: True

### Additional Information

I wouldn't like to use the blocklists because they cause extreme lag to the application when it's already laggy, Any workarounds to fix the "with Blocklists" lag or any notes to help in general?

**Comment by SkyWolfXP** [comment] 2024-05-05 08:37
I might have solved the lag issue while using the Blocklists, I disabled the ad-blocker cache in the `config.json`, I'm not entirely sure what this does but maybe I will rock with blocklists for now

**Comment by Ruboks-Cube** [comment] 2024-05-07 10:51
had the same issue, did it say, "sponsored" for you as well or something?

**Comment by Logging4J** [comment] 2024-05-08 02:28
having this issue aswell

**Comment by SuiSuii** [comment] 2024-05-08 13:16
having the same issue aswell

**Comment by ArjixWasTaken** [comment] 2024-05-10 22:34
duplicate of #1817

**Closed by ArjixWasTaken** 2024-05-10 22:34 UTC
