### ISSUE TITLE
[Bug]: (Synced Lyrics) In some unknown conditions, lyrics doesn't display even if lyrics exists and found on LRCLIB.

### ISSUE THREAD

**Issue by Dzheremi2** [th-ch/youtube-music#2332] opened 2024-08-04 13:19 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 40, kernel: 6.9.12-200.fc40.x86_64

### What CPU architecture are you using?

x64

### Reproduction steps

1. Play song
2. Open lyrics tab
2.1 Lyrics not displayed
3. Open DevTools > Network and find "search?*" request

### Expected Behavior

Lyrics displayed

### Actual Behavior

"No lyrics found for this song"
*See in additional information attached files*

### Enabled plugins

1. Downloader
2. In-app menu
3. Precise volume
4. Shortcuts (and MPRIS)
5. Discord Rich Presence
6. Music Together
7. Synced Lyrics

### Additional Information

![Снимок экрана от 2024-08-04 16-18-35](https://github.com/user-attachments/assets/49ba3299-1863-443e-abe7-7327c453df7f)

![Снимок экрана от 2024-08-04 16-12-33](https://github.com/user-attachments/assets/0ebfac5a-6c7e-46e3-ba9f-8de796f03d79)

**Comment by seba0456** [comment] 2024-08-04 18:50
I have the same issue on Windows 11 too.

**Comment by Toxijuice** [comment] 2024-08-06 17:17
I, too, am having this issue. I have not seen a single song that doesn't claim it hasn't found lyrics.
I can also confirm that while the lyrics do not populate, the fetch does return a valid response. 
There is no error logged in the console when this occurs.

I am running the Portable version on Windows 10.

**Comment by Dan-tk** [comment] 2024-08-07 22:06
> I, too, am having this issue. I have not seen a single song that doesn't claim it hasn't found lyrics. I can also confirm that while the lyrics do not populate, the fetch does return a valid response. There is no error logged in the console when this occurs.
> 
> I am running the Portable version on Windows 10.

did you find any fix?

**Comment by ArjixWasTaken** [comment] 2024-08-07 22:25
> I, too, am having this issue. I have not seen a single song that doesn't claim it hasn't found lyrics. I can also confirm that while the lyrics do not populate, the fetch does return a valid response. There is no error logged in the console when this occurs.
> 
> I am running the Portable version on Windows 10.

please provide a link so I can reproduce it myself

**Comment by ArjixWasTaken** [comment] 2024-08-07 22:30
for the song displayed in the issue's description I see that lrclib has the artist name as `Sam Tinnesz & Silverberg` but youtube music has it as `Silverberg & Sam Tinnesz`

the algorithm compares the artist name, and since it is way too different, it doesn't find a result

**Comment by ArjixWasTaken** [comment] 2024-08-07 22:31
for that, maybe we should split the artistname on &, to get multiple names

**Comment by Toxijuice** [comment] 2024-08-08 01:05
> did you find any fix?

Though I had trouble building an actual .exe to test, I built and previewed commit 32a572b, which appears to be working properly.

I assume commit ac51f79 is what fixed it, but can't guarantee that with 100% certainty.

> please provide a link so I can reproduce it myself

The issue was not with one or even a few songs. I tested dozens of songs, none of which worked but when checked the data returned did contain the correct song and lyrics, so it would seem that the current version (66816ac) doesn't display those lyrics for one reason or another.

Either way, the issue seems to be resolved for me in more recent commits. Unless the problem has something to do with the build process, in which case I will know in the next official release, as my electron-builder is refusing to spit out an executable.

**Comment by razeNFR** [comment] 2024-08-20 19:00
> > did you find any fix?
> 
> Though I had trouble building an actual .exe to test, I built and previewed commit [32a572b](https://github.com/th-ch/youtube-music/commit/32a572b35a98e9539132032bea0b1cb0d688b2f4), which appears to be working properly.
> 
> I assume commit [ac51f79](https://github.com/th-ch/youtube-music/commit/ac51f798c35b76195401d003bf311df87561419d) is what fixed it, but can't guarantee that with 100% certainty.
> 
> > please provide a link so I can reproduce it myself
> 
> The issue was not with one or even a few songs. I tested dozens of songs, none of which worked but when checked the data returned did contain the correct song and lyrics, so it would seem that the current version ([66816ac](https://github.com/th-ch/youtube-music/commit/66816ac42d271d261cf2490f59f8d417750d6b07)) doesn't display those lyrics for one reason or another.
> 
> Either way, the issue seems to be resolved for me in more recent commits. Unless the problem has something to do with the build process, in which case I will know in the next official release, as my electron-builder is refusing to spit out an executable.
> 
> EDIT: I resolved my build issue, which seems to be related to Windows path length. So I can more reliably confirm that as of the latest commit ([655741f](https://github.com/th-ch/youtube-music/commit/655741f108d7d9565b44b7c7a0b082b572763ebb)), synced-lyrics appears to be fully functional.

synced lyrics didnt work for me, how can i use your fix ?

**Comment by Toxijuice** [comment] 2024-08-20 20:25
> synced lyrics didnt work for me, how can i use your fix ?

Not my fix, those commits are from other people. I just manually built one of those commits. 

If the issue you're experiencing is the same that I was, it will be fixed when the next official release comes around.

If you don't want to wait, you can try building it yourself following the instructions [here](https://github.com/th-ch/youtube-music?tab=readme-ov-file#build). The build process is actually fairly straightforward, the only reason I had issues is because Windows has a hard time with longer paths. Cloning the repo to the root of a drive and building from there works just fine.

**Comment by razeNFR** [comment] 2024-08-21 14:44
> > synced lyrics didnt work for me, how can i use your fix ?
> 
> Not my fix, those commits are from other people. I just manually built one of those commits.
> 
> If the issue you're experiencing is the same that I was, it will be fixed when the next official release comes around.
> 
> If you don't want to wait, you can try building it yourself following the instructions [here](https://github.com/th-ch/youtube-music?tab=readme-ov-file#build). The build process is actually fairly straightforward, the only reason I had issues is because Windows has a hard time with longer paths. Cloning the repo to the root of a drive and building from there works just fine.

Ok thank you, i will wait for officiel update.

**Comment by Toxijuice** [comment] 2024-08-23 19:16
> Try clearing cache (options -> advanced -> clear app cache when app starts). After restarting the app, uncheck that.

This does not have an effect for me in the current release version (3.5.1 / 66816ac). In my case all evidence points to it being a parsing issue that is fixed in recent commits.

I would still recommend anyone having this issue to try that, and report if it fixes the problem. Just in the event there are multiple bugs with synced lyrics.

**Comment by vipkingo1** [comment] 2024-08-25 10:45
disabling my ad blocker seems to fix the issue for me or changing it to ad speedup instead of in player

**Comment by ArjixWasTaken** [comment] 2024-08-25 11:18
Let me clarify that this issue in particular is for songs have have multiple artists.

At least that is what the author of the issue is actually reporting.

Please make a different issue and give verbose details if you want your issue to get fixed.

**Closed** 2024-08-28 03:21 UTC

**Comment by HKGx** [comment] 2024-09-04 22:44
I've been having issues with lyrics - the requests certainly gets to LRCLIB and LRCLIB's response is alright.

Poking around with devtools I've noticed that this exact line:
https://github.com/th-ch/youtube-music/blob/48759559148c431bfc2935468cfeba71cb08f1b8/src/plugins/synced-lyrics/renderer/lyrics/fetch.ts#L94

When called, is causing an issue with Electron itself.
I'm getting:
```
TypeError: Failed to execute 'json' on 'Response': Illegal invocation at Object.apply 
```
at 
https://github.com/th-ch/youtube-music/blob/48759559148c431bfc2935468cfeba71cb08f1b8/src/plugins/adblocker/index.ts#L129-L133

I'm not really sure why that happens as I don't really have any sensible experience with Electron, so 🤷

**Comment by ArjixWasTaken** [comment] 2024-09-04 22:49
@HKGx please change the adblocker method to "ad speedup" or "with blocklists"

The "in player" mode is the reason of the error

Although, I remember @JellyBrick fixing that particular issue months ago

**Comment by HKGx** [comment] 2024-09-04 22:52
@ArjixWasTaken, I've disabled adbloker altogether as I'm paying for YT Premium. I just wanted to report an issue I've found. 😄
