### ISSUE TITLE
[Bug]: Cannot start application on Ubuntu 24

### ISSUE THREAD

**Issue by s-v-akinfiev** [th-ch/youtube-music#2794] opened 2024-12-28 07:05 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.7.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Ubuntu

### Operating System Version

24

### What CPU architecture are you using?

x64

### Reproduction steps

I have installed application with following commands:
>     wget https://github.com/th-ch/youtube-music/releases/download/v3.7.1/youtube-music_3.7.1_amd64.deb
>     sudo dpkg -i youtube-music_3.7.1_amd64.deb
>     sudo apt-get install -f
>     rm youtube-music_3.7.1_amd64.deb

When I start it it doesn't work:
![image](https://github.com/user-attachments/assets/776c62c8-3d2e-44b3-a13f-f76d9cca09b8)

I renamed directory '/opt/YouTube Music' to '/opt/YouTubeMusic'.
It helped.

### Expected Behavior

Application works

### Actual Behavior

It doesn't.

### Enabled plugins

Default plugins.

**Comment by JellyBrick** [comment] 2024-12-28 14:25
Duplicate of #2007

**Closed by JellyBrick** 2024-12-28 14:25 UTC
