### ISSUE TITLE
about

### ISSUE THREAD

**Issue by senolfndk** [th-ch/youtube-music#1767] opened 2024-02-19 21:39 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Can you add a site link?

### Proposed Solution

Can you add a site link?

### Alternatives Considered

Can you add a site link?

### Additional Information

![Ekran görüntüsü 2024-02-20 003526](https://github.com/th-ch/youtube-music/assets/52818836/cd18b68f-c046-4499-85f6-7014635fbdc7)

**Comment by ArjixWasTaken** [comment] 2024-02-19 21:42
> [x] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for a feature request that matches the one I want to file, without success.

I can confirm you have not done that :^)

**Comment by inson1** [comment] 2024-02-20 00:53
Duplicate of #1371

**Closed** 2024-02-20 02:49 UTC
Labels: duplicate
