### ISSUE TITLE
[Bug]: Media keys don't work

### ISSUE THREAD

**Issue by Joeeeeb5** [th-ch/youtube-music#1950] opened 2024-04-09 06:26 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.5.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### What CPU architecture are you using?

x64

### Reproduction steps

Press media keys on keyboard or mouse

### Expected Behavior

Song changes

### Actual Behavior

Playback isn't affected by media keys 

### Enabled plugins

1. Adblocker
2. Blur navigation bar
3. Bypass age restrictions
4. Compact sidebar
5. Expo volume
6. In-app menu
7. Skip silences
8. Taskbar media control
9. Video quality changer

### Additional Information

It'd be great to be able to change songs from my keyboard's media controls like on Spotify. I also wanna be able to disable that windows 10 notification when using media keys

**Comment by JellyBrick** [comment] 2024-04-11 09:26
Duplicate of #1949

**Closed by JellyBrick** 2024-04-11 09:26 UTC
Labels: duplicate
