### ISSUE TITLE
Does not integrate properly with Linux KDE media player widget (minor bug)

### ISSUE THREAD

**Issue by ranenvious** [th-ch/youtube-music#883] opened 2022-11-17 01:46 UTC
The KDE media player widget does properly pause, skip, etc. however it's audio control does not work. No matter what I set the audio to via KDE's media player widget the audio coming from the app itself remains constant. I don't think it's an issue with the widget itself since the widget works perfectly fine with even the in-browser youtube website when it comes to controlling audio and whatnot. (If I change the value on the website it resets, but it DOES change the audio) 

Minor issue but as someone who tends to use that widget to change volume quickly it's one I'm increasingly noticing. 
(tested on uptodate EndeavourOS installation)

**Comment by JellyBrick** [comment] 2023-10-07 09:20
Duplicate of #1236

**Closed by JellyBrick** 2023-10-07 09:20 UTC
