### ISSUE TITLE
[Bug]: cursor blocked when i want to select next song (MacOS and Windows)

### ISSUE THREAD

**Issue by dl3c01n** [th-ch/youtube-music#1502] opened 2023-12-07 09:58 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.0.2

### What operating system are you using?

macOS

### Operating System Version

MacOS 14 (but same issue on Windows)

### What arch are you using?

arm64 (including Apple Silicon)

### Reproduction steps

Just select a song first, but then, in the sidebar of the player, when you want to select a song, the curser is blocked. (check the cursor image 1 and where it happens image 2)

<img width="125" alt="image" src="https://github.com/th-ch/youtube-music/assets/35270127/54a8d3e4-7103-4a7c-afd4-f12fa350f1ff">

<img width="604" alt="image" src="https://github.com/th-ch/youtube-music/assets/35270127/1dac7547-cdd0-45a3-be39-ce1e5c5038eb">

### Expected Behavior

It should not be blocked.

### Actual Behavior

Next songs are not selectable.

### Enabled plugins

Adblocker (only)

**Comment by ArjixWasTaken** [comment] 2023-12-07 10:10
Possibly duplicate of #1432

**Closed** 2023-12-07 13:34 UTC
