### ISSUE TITLE
Cannot search

### ISSUE THREAD

**Issue by ItsElectra** [th-ch/youtube-music#284] opened 2021-05-14 20:14 UTC
I can't type in the search box. 
![image](https://user-images.githubusercontent.com/59057998/118323755-1f392200-b4cf-11eb-96a3-41e779eae19f.png)
Those are the plugins I turned on.
I haven't changed any settings besides enabling Systray and resume last.
halp

**Comment by Araxeus** [comment] 2021-05-14 20:18
Duplicate of #256

This is happens only in the preview release v1.12.0

Please use v1.11.0 or build from main branch (this has already been fixed)

**Closed** 2023-02-08 22:30 UTC
