### ISSUE TITLE
[Bug]: not caching music  

### ISSUE THREAD

**Issue by Chill-Akash** [th-ch/youtube-music#1918] opened 2024-04-01 13:34 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

 youtube-music-3.3.5.x86_64.rpm 

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other (specify below)

### Operating System Version

Fedora 39, Linux fedora 6.7.9-200.fc39.x86_64

### What CPU architecture are you using?

x64

### Reproduction steps

you can reproduce same issue just by putting any music in 1 loop. 

### Expected Behavior

it is expected that it should start the looped music without loading back from the server 

### Actual Behavior

but it loads the song back from the server. I verify this from internet data speed meter (network traffic monitor).

### Enabled plugins

and almost all the plugins are enabled. 

### Additional Information

i am not sure but cause of this the crossfade is not working properly.

**Comment by JellyBrick** [comment] 2024-04-03 00:27
- It's a YouTube's policy.
- Duplicate of #1148

**Closed by JellyBrick** 2024-04-03 00:27 UTC
