### ISSUE TITLE
Downloader Stuck On Downloading

### ISSUE THREAD

**Issue by Rarab5534** [th-ch/youtube-music#338] opened 2021-06-26 15:12 UTC
Hi its Rarab again

So i went to download some songs and then my Youtube Music started doing this strange thing that i have never saw before
![image](https://user-images.githubusercontent.com/86423147/123517505-46bc0680-d699-11eb-9623-8f75975538bf.png)

So is this a bug? or just known?

**Comment by Bellisario** [comment] 2021-06-26 19:28
This not a very bug... you watch the download only by text and not by icon, so, if the problem is that you see a download icon with a strange pixel, this is not a progress.
If this is not the problem, I can say you that you need only to wait some time to see downloading title, conversion title, etc., this is only because this has been configured not to see a very accurate progress but only action that the download is doing.

P.S.: if you don't want to see download button you can just disable the plugin.

**Comment by th-ch** [comment] 2021-06-26 21:32
Hey @Rarab5534 and @Bellisario , this issue is confirmed because some APIs have changed and upstream dependencies are being updated at the moment - https://github.com/fent/node-ytdl-core/pull/938 has now been merged, just need to check if everything works ok with the new version, keeping this issue opened in the meantime!

**Comment by Rarab5534** [comment] 2021-06-27 07:55
Well how do i download it? and install it to youtube music then?

**Comment by Bellisario** [comment] 2021-06-27 09:30
@Rarab5534, you can't... so, or you need to build yourself the executable as a dev, or you need to await the next release.

**Comment by Rarab5534** [comment] 2021-06-27 15:43
ok

**Closed** 2021-06-27 19:10 UTC

**Comment by th-ch** [comment] 2021-06-27 19:13
Hey @Rarab5534 & @Bellisario, #339 has been merged and should fix the plugin, it will land in the next version! (which will probably be released soon)
