### ISSUE TITLE
[Bug]: brew cask can't load application due to No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by YXXJIA005** [th-ch/youtube-music#1514] opened 2023-12-09 20:08 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.0.2

### What operating system are you using?

macOS

### Operating System Version

14.1.2 Sonoma

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working YouTube Music (Application) version

3.0.2

### Reproduction steps

brew upgrade

### Expected Behavior

brew upgrades everything

### Actual Behavior

When loading all casks for update when it reaches youtube music it fails and I can't upgrade or uninstall casks anymore via brew.
Error: No such file or directory @ rb_sysopen - https://api.github.com/repos/th-ch/youtube-music/releases/latest

### Enabled plugins

None

**Comment by JellyBrick** [comment] 2023-12-09 23:40
Duplicate of #1496

fixed at #1496

**Comment by JellyBrick** [comment] 2023-12-12 01:08
It should fixed by #1496, but it seems doesn't.

**Comment by LucianoAngel** [comment] 2023-12-23 17:42
same issue here.

**Comment by JellyBrick** [comment] 2023-12-24 18:40
https://stackoverflow.com/questions/65937714/no-such-file-or-directory-rb-sysopen-for-external-url-rails-6-11-ruby-3

🤔

**Comment by indianets** [comment] 2023-12-27 05:35
I think this is not the best way to have Homebrew local cask. There should be another repository dedicated to brew exactly named `homebrew-youtube-music` under `th-ch` (or any other github account, but this is best to identify and keep it in his account) and have just `youtube-music.rb` cask definition inside that, after which users would just need these --

```
brew tap tc-ch/youtube-music
brew install youtube-music
```

tap is needed once only on any system, Homebrew will automatically fetch the latest cask definition from github and install whatever is mentioned there.

**Comment by th-ch** [comment] 2023-12-29 10:28
👋 Thanks for raising the issue! https://github.com/th-ch/homebrew-youtube-music has been created and [this repo updated](https://github.com/th-ch/youtube-music/commit/f46c431f4c303a39a7ac0bd8adf583e34f836e94)! Closing, feel free to reopen if needed 😃

**Closed by th-ch** 2023-12-29 10:28 UTC
Labels: bug, help wanted

**Comment by Lumca** [comment] 2024-01-12 16:53
I have installed the youtube music, I am happy with it but what ever I do:
`brew doctor`
or
`brew uninstall youtube-music`

I get 
`Error: No such file or directory @ rb_sysopen - https://api.github.com/repos/th-ch/youtube-music/releases/latest`

not sure how to fix that.

**Comment by indianets** [comment] 2024-01-12 16:58
@Lumca Try once with the repo I made as an example. It has brew-styled cask formula which I proposed to be added.
