### ISSUE TITLE
[Bug]: Crossfade turned on randomly mutes songs playing

### ISSUE THREAD

**Issue by pinkkuh** [th-ch/youtube-music#1285] opened 2023-10-08 12:09 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.0.2 

### Expected Behavior

The songs playing should just be playing as Normal throughout its duration with crossfade (beta) turned on.

### Actual Behavior

The song randomly mutes (mute as in NO SOUND, FULL VOLUME in player) for X seconds and comes back playing unmuted with the crossfade (beta) turned on.

### Additional Information

Although the crossfade feature is still in beta. I just thought of reporting it because I loved the crossfade and the latest update made some small issues for me.
I disabled all plugins and turned them on one by one to trace what was causing it and found that the crossfade (beta) was causing it *in my PC. (I do not know if its the same for others).
I disabled crossfade plugin in my PC for now because of the issue.

**Comment by JoqniX** [comment] 2023-10-10 06:33
im also having the same issue!

**Comment by JellyBrick** [comment] 2024-01-16 13:53
Duplicate of #1633

fixed at d5ab36f42ef3be89de33728f472681d975c9c47d

**Closed by JellyBrick** 2024-01-16 13:53 UTC
Labels: bug
