### ISSUE TITLE
[Bug]: Ads not being blocked while using the " In-Player " adblocker

### ISSUE THREAD

**Issue by XCalibur5678** [th-ch/youtube-music#1817] opened 2024-03-02 13:36 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 22631.3155

### What CPU architecture are you using?

x64

### Reproduction steps

1. Switch to Plugins>Adblocker>Blocker>In Player
2. Play any song

### Expected Behavior

Music to play without any ads 

### Actual Behavior

2 30 seconds ads playing

### Enabled plugins

1. Adblocker
2. Album Actions
3. Blur Navigation Bar
4. Downloader
5. In app Menu
6. Lyrics Genius
7. Navigation
8. SponsorBlock
9. Taskbar media control
10. Video Toggle

### Additional Information

If using the In player ad blocker , ads aren't being blocked . Using the " blocklists " function mitigates this issue . Hereby attaching a screenshot of the ad playing . Please feel free to reach out to me if you need any more information, 

![image](https://github.com/th-ch/youtube-music/assets/98412450/26c95c8d-a84c-4612-b5be-1d16ac327c9a)

**Comment by Joey451-OG** [comment] 2024-03-19 20:51
I can confirm this is happening on Linux as well:

Linux Version:
Ditro: Fedora 39
Architeture: x86_64

Version: 3.3.2

Enabled Plugins:
1. Adblocker (In-Player)
2. Discord Rich Presence
3. Navigation

Please let me know if I can be of further assistance. I love using this tool :D

![image](https://github.com/th-ch/youtube-music/assets/60891047/13e99d30-f881-4995-b343-f0e71a797318)

**Comment by BrandTruong** [comment] 2024-03-26 06:13
Also have this issue. Swapping between in-player and blocklist does nothing and ads still appear.

OS: Windows 10 Home 
OS Version: 10.0.19045 Build 19045
System Type: x64-based PC

YT Music Version: 3.3.4

Plugins Enabled:
Ad Blocker
Album Color Theme
Discord Rich Presence
Downloader
In-App Menu
Navigation
Sponsorblock

**Comment by frrrrrits** [comment] 2024-03-27 04:21
did this issue fixed? using 3.3.5 still appeared.

**Comment by JellyBrick** [comment] 2024-03-27 17:58
> did this issue fixed? using 3.3.5 still appeared.

YT has changed the logic to show ads. Please use `blocklists` mode until we figure it out.

**Comment by Trixarian** [comment] 2024-04-11 11:37
I'm going to copy my solution here:

> Toggle with blocklists under Blocker in the ad blocker Plugin. Go to Options---> Advanced options---> Edit config.json and change:
> 
> ``` json
> 
> 			"additionalBlockLists": [],
> ```
> to
> ``` json
> 			"additionalBlockLists": [
> 				"https://filters.adtidy.org/extension/ublock/filters/122_optimized.txt"
> 			],
> ```
> and restart the app
> That solves the ads issue for me

Adherence to protocol is fine, but don't use it to needlessly burying the issue and solutions to it

**Comment by Joey451-OG** [comment] 2024-04-11 15:31
If I'm not mistaken, it looks like Ublock Origin uses this service (adtidy.org).

We should add it to the default block list [here](https://github.com/th-ch/youtube-music/blob/master/src/plugins/adblocker/blocker.ts).

**Comment by Trixarian** [comment] 2024-04-11 15:39
> If I'm not mistaken, it looks like Ublock Origin uses this service (adtidy.org).
> 
> We should add it to the default block list [here](https://github.com/th-ch/youtube-music/blob/master/src/plugins/adblocker/blocker.ts).

It's an optimized list maintained by AdGuard. It's generally lighter on resources and more up to date than the list featured in the adblockers themselves - since the one I'm using (Fanboy Annoyances) /is/ on that lists, just out of date. Why I prefer them over uBlock Origin's in general

**Comment by lucastwg** [comment] 2024-04-11 21:50
+1, blocklist is working fine.

**Comment by JellyBrick** [comment] 2024-04-13 07:45
`Blocklist` mode is fixed by #1966

**Comment by peppepascale** [comment] 2024-05-01 17:14
> I'm going to copy my solution here:
> 
> > Toggle with blocklists under Blocker in the ad blocker Plugin. Go to Options---> Advanced options---> Edit config.json and change:
> > ```json
> > 			"additionalBlockLists": [],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```json
> > 			"additionalBlockLists": [
> > 				"https://filters.adtidy.org/extension/ublock/filters/122_optimized.txt"
> > 			],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and restart the app
> > That solves the ads issue for me
> 
> Adherence to protocol is fine, but don't use it to needlessly burying the issue and solutions to it


where to put this line in the json? i'm trying everything. Ads still there

**Comment by peppepascale** [comment] 2024-05-01 18:00
i think i found how to activate this, had to switch to "block list" in the app:
plugins/ad-blocker/block/   then  block list
then the line appears in the json and i was able to fill like explained above.
lets see if works now

**Comment by DereC4** [comment] 2024-05-05 09:15
This is not anything bad, but correct me if i'm wrong, back in 2023 didn't we decide to switch to "In Player" because of the RAM usage leak that was happening from the "Blocklists" option? 

Did we ever fix that? I got busy with university so I had to temporarily drop this project

**Comment by JellyBrick** [comment] 2024-05-11 01:27
@DereC4 Yes, that issue has been resolved.

**Comment by VeryHolyCheeeese** [comment] 2024-05-14 10:07
If this is the definitive fix to the issue of ads not being blocked then shouldn't this be pushed in the next update?

**Comment by farsdewibs0n** [comment] 2024-05-14 19:26
> [#1955 (comment)](https://github.com/th-ch/youtube-music/issues/1955#issuecomment-2047699372) is also a viable fix. Using a link instead of a path removes the need to download the list

Note that this solution breaks search feature.

**Comment by velaton618** [comment] 2024-05-17 17:15
This is happening on Mac as well:

Macbook air m2 
Sonoma 14.4.1
Architeture: arm64 

Enabled plugins:
- All the default ones(didn't change anything)

Version: 3.3.6

**Comment by DereC4** [comment] 2024-05-17 22:02
> @DereC4 Yes, that issue has been resolved.

neat

**Closed** 2024-06-01 00:49 UTC
Labels: bug, fix-available

**Comment by JellyBrick** [comment] 2024-06-01 00:50
Fixed at 1f1efac4660fb7d0867cd67d9b9f6776331f4638

**Comment by DereC4** [comment] 2024-06-04 03:05
neat
