### ISSUE TITLE
[Feature Request]: All songs from YoutubeMusic, not Youtube

### ISSUE THREAD

**Issue by Johndjk** [th-ch/youtube-music#1891] opened 2024-03-26 15:05 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It's a problem when you're listening to a song and there are lots of effects and parts that aren't part of the song but are from the music video.

### Proposed Solution

All songs from YoutubeMusic, if possible

### Alternatives Considered

All songs from YoutubeMusic, if possible

**Comment by JellyBrick** [comment] 2024-03-26 16:21
Duplicate of #1383

**Closed by JellyBrick** 2024-03-26 16:21 UTC
