### ISSUE TITLE
[Bug]: Ad blocker not working on Macbook

### ISSUE THREAD

**Issue by AchyParts** [th-ch/youtube-music#2142] opened 2024-06-11 06:20 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [x] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4.1

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Reproduction steps

1. Open the app
2. Enable the Ad Blocker plugin
3. Play a song, and an ad is likely to play in the player

### Expected Behavior

No ads will play in the player.

### Actual Behavior

Ads play in the player at the normal rate, as if the plugin isn't enabled.
<img width="809" alt="Screenshot 2024-06-10 at 11 16 26 PM" src="https://github.com/th-ch/youtube-music/assets/172355226/4d80dbb9-9958-4124-9ed7-55d5eeeded2f">

### Enabled plugins

1. Ad Blocker
2. Album Color Theme
3. Ambient Mode
4. Disable Autoplay
5. Discord Rich Prescence
6. Downloader
7. In-app Menu
8. 

### Additional Information

I am not very proficient in coding.
I also have the plugin enabled as blocking in player, so I'm not sure if that has anything to do with my issue.
<img width="450" alt="Screenshot 2024-06-10 at 11 19 26 PM" src="https://github.com/th-ch/youtube-music/assets/172355226/56b1f2db-760b-4b05-8c01-dc343d97b412">

**Comment by sumit4613** [comment] 2024-06-26 12:18
Facing same issue.

**Comment by JellyBrick** [comment] 2024-06-29 00:47
Duplicate of #2150

**Closed by JellyBrick** 2024-06-29 00:47 UTC
