### ISSUE TITLE
[Bug]: the proxy does not work in any way

### ISSUE THREAD

**Issue by vleky** [th-ch/youtube-music#2344] opened 2024-08-08 12:41 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19044.4291

### What CPU architecture are you using?

x64

### Reproduction steps

1. I entered the proxy through the program settings, in the form of socks5://ip:port:login:password
2. after restarting, there is no Internet connection, although the proxy is obviously working

### Expected Behavior

the program will start working stably, but with a proxy, not physical and not my real ip

### Actual Behavior

the program does not load in any way, even without a username and password, even if i change socks5 to html

### Enabled plugins

nope, i didnt enable anything

**Comment by ArjixWasTaken** [comment] 2024-08-08 13:17
> the program does not load in any way, even without a username and password, even if i change socks5 to html

did you mean http?

**Comment by vleky** [comment] 2024-08-08 13:19
> > the program does not load in any way, even without a username and password, even if i change socks5 to html
> 
> did you mean http?

yes, I'm sorry, wrote it by mistake

**Comment by ArjixWasTaken** [comment] 2024-08-08 13:26
We rely on electron's [proxy-server](https://www.electronjs.org/docs/latest/api/command-line-switches#--proxy-serveraddressport) command line option.

But electron does not do anything different from chromium, so their documentation looks wrong.
Chromium's [command line options](https://www.chromium.org/developers/design-documents/network-settings/#command-line-options-for-proxy-settings) for proxies shows `--proxy-server="http=foopy:80;ftp=foopy2"` as an example.

That'd mean you have to input `http=foopy:80` as the proxy, and not `http://foopy:80`, or just `foopy:80`.
Have you been inputting the value in any of the above formats?
If not please try it like that

**Comment by vleky** [comment] 2024-08-08 13:32
I'm trying to enter a proxy like this: at the top of the program "settings" - "advanced settings" - "set proxy", but the pop-up window requires input in the format "http://ip:port " or "socks5://ip:port"

**Comment by ArjixWasTaken** [comment] 2024-08-08 13:33
I see that neither works.
Even when I manually edit the config to force a different format, it doesn't work.

I'll investigate it for a bit

**Comment by ArjixWasTaken** [comment] 2024-08-08 13:37
ok so, manually edit the config

![image](https://github.com/user-attachments/assets/a992fba4-16ad-47df-af56-0cffd339a576)

and set your proxy like this
![image](https://github.com/user-attachments/assets/e45c97fa-376a-4a88-a54d-5e364eeac6d7)

**with the `http=` in front**

Save the file, and restart youtube music.
Does it work then?

---

That is an anonymous free proxy I found online, so I won't censor it.

**Comment by ArjixWasTaken** [comment] 2024-08-08 13:46
I hid my comment since it didn't actually solve the issue.
the `http=` applied the proxy only on `http://` and not `https://` requests.

changing it to `https=` has the same issue

**Comment by vleky** [comment] 2024-08-08 13:49
the proxy function is working, but if I choose even the closest and most accessible proxy (10-20 ms), the program loads for a very long time. there is a playback bar at the bottom, a search at the top, it is there, but no albums, no tracks, no profile, nothing is loaded

**Comment by vleky** [comment] 2024-08-08 13:51
i will try to reinstall YTM app, maybe it gave some results

**Comment by JellyBrick** [comment] 2024-08-08 14:24
Duplicate of #743

**Closed by JellyBrick** 2024-08-08 14:24 UTC

**Comment by vleky** [comment] 2024-08-08 14:31
> Duplicate of #743

I disagree, solve this problem, and does not say that it is a duplicate. this is a duplicate of a problem that was sent to websites to solve, where there is still no solution.

**Comment by JellyBrick** [comment] 2024-08-08 23:22
> even if it is a duplicate, **no one** has provided a solution to the problem

"Duplicate" **does not mean** the problem is solved.

**Comment by JellyBrick** [comment] 2024-08-08 23:26
Also, Chromium itself does not support authenticated proxies, which is why that issue remains open.

**Comment by JellyBrick** [comment] 2024-08-08 23:26
![IMG_0829](https://github.com/user-attachments/assets/dfdc0720-3299-4067-9c00-44f0a5af2b86)
😅
