### ISSUE TITLE
[Bug]: Error Downloading Songs to Destktop

### ISSUE THREAD

**Issue by Mendungo** [th-ch/youtube-music#2750] opened 2024-12-20 19:47 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.2

### Reproduction steps

enable download plug it
choose download folder
click "download" from song options
error pops up on screen 

![Screenshot 2024-12-20 143956](https://github.com/user-attachments/assets/8e03cdf1-d78e-448b-841d-bdf62ca07a15)

### Expected Behavior

Download song/Playlist

### Actual Behavior

Error Window Pops up

### Enabled plugins

Download
ad blocker
navigation

**Comment by Mendungo** [comment] 2024-12-20 20:01
I've been using your mod for quite some time and there always seems to be a downloading issue very few updates, i decided not to update the App anymore but it still gets to me somehow on older versions.
friendly opinion, way too many updates being released often on a pretty stable software which causes issues in the way on things that weren't broken

**Comment by thijsi123** [comment] 2024-12-20 22:23
I have the same issue, (off-topic: I've also noticed that the app has trouble buffering or at least continuing from being paused for like... A few minutes.)

**Comment by daika7ana** [comment] 2024-12-21 00:56
Duplicate of #2628.

For Windows users, a build with the fix is available in discussion #2726, shared by another user. Please keep in mind that this is not an official tagged release, so proceed with caution if you choose to download it. Waiting for the official release is strongly recommended.

**Comment by JellyBrick** [comment] 2024-12-21 03:18
> friendly opinion, way too many updates being released often on a pretty stable software which causes issues in the way on things that weren't broken

First, that issue was caused by a structural change on the YouTube. (not caused by an update)
Second, update to the next release to fix that issue.

And, did you read the preflight checklist?

Duplicate of #2628

**Closed by JellyBrick** 2024-12-21 03:18 UTC
