### ISSUE TITLE
[Bug]: ERROR: Unexpected token (1:71)

### ISSUE THREAD

**Issue by topakopa** [th-ch/youtube-music#2706] opened 2024-12-12 20:08 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2-1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

6.11.10-2-MANJARO

### What CPU architecture are you using?

x64

### Reproduction steps

1. Try Download any file
2. Get this ![изображение](https://github.com/user-attachments/assets/998bbb12-02eb-4c64-90d5-ee7fc83cd459)

### Expected Behavior

.

### Actual Behavior

.

### Enabled plugins

1. video-toggle
2. precise-volume
3. discord
4. bypass-age-restrictions
5. downloader
6. album-color-theme
7. sponsorblock

**Comment by Dark5lalom** [comment] 2024-12-13 01:48
Also having the same error with error 1:71 on Windows 11 24H2 on 3.6.2.0

**Comment by JellyBrick** [comment] 2024-12-13 02:38
READ PREFLIGHT CHECKLIST

**Comment by JellyBrick** [comment] 2024-12-13 02:38
Duplicate of https://github.com/th-ch/youtube-music/issues/2691, https://github.com/th-ch/youtube-music/issues/2628

**Closed by JellyBrick** 2024-12-13 02:38 UTC
