### ISSUE TITLE
[Bug]: YT Music reports an incorrect playback position and duration to the operating system

### ISSUE THREAD

**Issue by ungive** [th-ch/youtube-music#2798] opened 2024-12-28 14:44 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.7.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Version	10.0.19045 Build 19045

### What CPU architecture are you using?

x64

### Reproduction steps

1. Download msd.exe from https://github.com/ungive/media-session-dump/releases/tag/build2
msd.exe is a program that shows what media is playing on the system and its metadata, an example of the output can be seen here: https://github.com/ungive/discord-music-presence/issues/131#issuecomment-2543085882
2. Play a song with YT Music for Desktop and wait until it ends and the next song in the queue plays
3. Observe that the "Position (live)" and "duration" ("EndTime - StartTime") have values that do not correspond to the playback position and duration of the currently playing song

### Expected Behavior

The position should be reset back to 0 once the next song starts.

### Actual Behavior

The playback position continues on as if the same song kept playing, even though another song is playing.

### Enabled plugins

1. Default

### Additional Information

I'm just forwarding information from this issue: https://github.com/ungive/discord-music-presence/issues/131

It also seems to not be reproducible all the time.

![395782806-ea126259-9fa5-4c4c-9af9-d34f45d405fc](https://github.com/user-attachments/assets/a6ff4025-c8fd-4b63-9bef-1b1c18511a88)
Also see my comment here: https://github.com/ungive/discord-music-presence/issues/131#issuecomment-2543114292

**Comment by JellyBrick** [comment] 2024-12-28 14:58
Duplicate of #2621

**Closed by JellyBrick** 2024-12-28 14:58 UTC
