### ISSUE TITLE
[Bug]: Man my issue still persists I STILL CAN'T LOG IN INTO MY ACC

### ISSUE THREAD

**Issue by MountainGuy1** [th-ch/youtube-music#2108] opened 2024-06-01 13:40 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.9

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.0.0

### Reproduction steps

none

### Expected Behavior

To let me log in without me getting stuck on a black screen

### Actual Behavior

My prev issue is still there when attempting to log in cause I was automatically logged out when listening to my playlist. I get a black screen just like in the prev version 3.3.6. Cleared the temps again but still there again waited for half an hour.
![YouTube Music 01-06-2024 19_08_49](https://github.com/th-ch/youtube-music/assets/167510562/ffa018b8-a515-439f-8f7b-58592f2e789f)

### Enabled plugins

![YouTube Music 01-06-2024 19_09_46](https://github.com/th-ch/youtube-music/assets/167510562/e0d4f0ad-9c99-4530-9a61-68c2f53502c6)
![YouTube Music 01-06-2024 19_09_50](https://github.com/th-ch/youtube-music/assets/167510562/14ef6c06-fa2c-46a6-95d2-8929fdd715a7)

**Comment by JellyBrick** [comment] 2024-06-01 17:47
Duplicate of #2103

**Closed by JellyBrick** 2024-06-01 17:47 UTC
