### ISSUE TITLE
[Bug]: Selecting/moving songs from autoplay/up next list isn't working.

### ISSUE THREAD

**Issue by Ao1Pointblank** [th-ch/youtube-music#1504] opened 2023-12-07 20:55 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.0.2 amd64

### What operating system are you using?

Other (specify below)

### Operating System Version

Linux Mint 21.2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

NA (is a youtube issue)

### Reproduction steps

Start a radio playlist.

Scroll down past the queue, to the part of the queue that shows the algorithmically generated song list. 

Attempt to move one of these songs with the cursor into the main queue (it will show the drag crosshair no matter what you hover over in this area)

Alternatively, try to click the thumbnail to play one of these songs. Cursor will still show drag crosshair icon instead of pointer

### Expected Behavior

Should be able to drag these songs to queue or click them to play immediately.

### Actual Behavior

Completely unable to interact with the songs lined up after the immediate queue

### Enabled plugins

1. Adblocker (in player)
2. Bypass Age Restrictions
3. Compact Sidebar
4. Discord Rich Presence
5. Downloader
6. Exponential Volume
7. Last.fm
8. Lyrics Genius
9. Navigation
10. Precise Volume
11. SponsorBlock
12. Video Toggle (force remove)

### Additional Information

I tried disabling all the plugins and also installed app versions 3.0.0 and 3.0.1 to no effect.

**Comment by JellyBrick** [comment] 2023-12-07 23:10
It's not th-ch/youtube-music's issue.

Duplicate of #1432

**Closed** 2023-12-07 23:10 UTC
Labels: duplicate, youtube-music-issue
