### ISSUE TITLE
MPRIS is not registered anymore

### ISSUE THREAD

**Issue by dgalli1** [th-ch/youtube-music#872] opened 2022-11-04 12:59 UTC
In the newest Version the custom mpris controller doesn't seem to work anymore.
Which has the effect that Song Thumbnail will not be displayed on Linux anymore.

**Comment by aacebedo** [comment] 2022-11-10 21:10
I confirm. MPRIS not working on 1.18.0. Was working on 1.17.0

**Comment by dgalli1** [comment] 2022-11-11 17:25
Issue probably lies in this unmaintained dependency:
https://github.com/dbusjs/node-dbus-next/issues/111

**Comment by aacebedo** [comment] 2022-12-14 20:28
Is this bug acknowledged? My distro package has been updated and mpris control is now broken :(

**Comment by aacebedo** [comment] 2022-12-16 11:49
I solved the issue by deactivating the shortcuts

**Comment by dgalli1** [comment] 2022-12-16 12:16
It randomly started working again for me on arch linux 1.18.

Anyone still got this issue or can this be closed?

**Comment by aacebedo** [comment] 2022-12-16 12:43
I don't think so. The artwork is not working and it means the shortcut functionality is not working completely.

**Comment by dgalli1** [comment] 2022-12-16 14:01
That's what I mean i could enable shortcuts again. And everything seems to work now for me. (electron19)

**Comment by Scridgeon** [comment] 2023-01-20 22:55
I never had shortcuts enabled and MPRIS never worked. I'm using the 1.19 deb.

**Comment by Araxeus** [comment] 2023-01-20 23:02
> Issue probably lies in this unmaintained dependency: [dbusjs/node-dbus-next#111](https://github.com/dbusjs/node-dbus-next/issues/111)

to be fair, we are using mpris-service, which is a different package which is even more unmaintained:
https://github.com/dbusjs/mpris-service/blob/81665c48ec8912aee210407e60d4b3bc114894b3/package.json#L30

Even the dbus-next version there isn't the latest… 😂

Since I can't find any other dbus mpris implementations, the only solution that I can see would be to downgrade to electron<20
which isn't going to happen just for this

**Comment by dgalli1** [comment] 2023-01-20 23:05
`error time=1674255652.135471 sender=org.freedesktop.DBus -> destination=:1.139687 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=15
   string "The name org.mpris.MediaPlayer2.youtube-music was not provided by any .service files"
method call time=1674255652.135501 sender=:1.139687 -> destination=org.freedesktop.DBus serial=16 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.mpris.MediaPlayer2.youtube-music"
method return time=1674255652.135503 sender=org.freedesktop.DBus -> destination=:1.139687 serial=17 reply_serial=16
   string ":1.129562"
method call time=1674255652.135530 sender=:1.139687 -> destination=:1.129562 serial=17 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.mpris.MediaPlayer2.Player"
error time=1674255652.135894 sender=:1.129562 -> destination=:1.139687 error_name=com.github.dbus_next.ServiceError reply_serial=17
   string "Service error: The service threw an error.
TypeError: DBusError is not a constructor
    at PlayerInterface.LoopStatus (/usr/lib/youtube-music/app.asar/node_modules/mpris-service/src/interfaces/player.js:118:13)
    at handleGetAllProperties (/usr/lib/youtube-music/app.asar/node_modules/dbus-next/lib/service/handlers.js:125:22)
    at handleStdIfaces (/usr/lib/youtube-music/app.asar/node_modules/dbus-next/lib/service/handlers.js:240:7)
    at handleMessage (/usr/lib/youtube-music/app.asar/node_modules/dbus-next/lib/service/handlers.js:280:7)
    at handleMessage (/usr/lib/youtube-music/app.asar/node_modules/dbus-next/lib/bus.js:136:21)
    at EventEmitter.<anonymous> (/usr/lib/youtube-music/app.asar/node_modules/dbus-next/lib/bus.js:151:9)
    at EventEmitter.emit (node:events:527:28)
    at /usr/lib/youtube-music/app.asar/node_modules/dbus-next/lib/connection.js:116:14
    at Socket.<anonymous> (/usr/lib/youtube-music/app.asar/node_modules/dbus-next/lib/message.js:63:9)
    at Socket.emit (node:events:527:28)"
method call time=1674255652.135971 sender=:1.139687 -> destination=org.freedesktop.DBus serial=18 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.mpris.MediaPlayer2.youtube-music'"
method return time=1674255652.135973 sender=org.freedesktop.DBus -> destination=:1.139687 serial=18 reply_serial=18
signal time=1674255652.136115 sender=org.freedesktop.DBus -> destination=:1.139687 serial=247 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.139687"
signal time=1674255652.136118 sender=org.freedesktop.DBus -> destination=(null destination) serial=69779 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
`

It's really wierd with playerctl im getting this error but KDE seems to be able to control it without any issue. But yes issue is definitly in the dbus implementation.

**Comment by amplexus** [comment] 2023-04-16 01:20
I raised a https://github.com/dbusjs/mpris-service/pull/52 to fix this. Tested locally (Ubuntu 22.10) with playerctl and youtube-music (built from source) and works for me.

**Comment by amplexus** [comment] 2023-04-17 10:33
I raised a https://github.com/dbusjs/mpris-service/pull/52 to fix this. Tested locally (Ubuntu 22.10) with playerctl and youtube-music (built from source) and works for me.

See also https://github.com/th-ch/youtube-music/issues/971

**Comment by JellyBrick** [comment] 2023-10-07 08:48
Duplicate of #971

**Closed by JellyBrick** 2023-10-07 08:48 UTC
Labels: bug
