### ISSUE TITLE
[Feature Request]: Feature Request: Implement Collaborative Playlist Creation

### ISSUE THREAD

**Issue by KhNediem** [th-ch/youtube-music#1912] opened 2024-03-31 12:33 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, our project lacks the functionality for collaborative playlist creation. This feature would allow users to create playlists together with their friends, enabling a more social and interactive experience within the app.

### Proposed Solution

- Implement a feature that allows users to invite friends to collaborate on playlist creation.
- Enable real-time editing and updating of collaborative playlists by all invited users.
- Provide options for users to control permissions (e.g., editing rights) for collaborators.

### Alternatives Considered

As an alternative approach, integrating with existing social platforms (e.g., Facebook, Twitter) to facilitate playlist collaboration. However, this approach may pose privacy concerns and limit the user base to those who have accounts on the integrated platforms. 

### Additional Information

Further research is needed to collect user feedback and refine the proposed solution. This survey aims to develop a persona for the app to enhance understanding.
https://forms.office.com/r/aeFcy7gG7m

**Comment by JellyBrick** [comment] 2024-03-31 14:46
https://github.com/th-ch/youtube-music/tree/master/src/plugins/music-together

Already implemented.

**Comment by JellyBrick** [comment] 2024-03-31 14:46
Duplicate of #1480

**Closed by JellyBrick** 2024-03-31 14:46 UTC
Labels: duplicate
