### ISSUE TITLE
[Bug]: Error: net::ERR_FAILED on downloader

### ISSUE THREAD

**Issue by Zyanbob** [th-ch/youtube-music#2315] opened 2024-08-01 20:54 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home version 22H2

### What CPU architecture are you using?

x64

### Reproduction steps

1.Enable downloader

### Expected Behavior

Downloads playlists

### Actual Behavior

This error message on half of the songs:
![Screenshot 2024-08-02 062901](https://github.com/user-attachments/assets/e1af42da-998c-45d5-a057-a694ad69d9cb)

### Enabled plugins

1.Ad blocker
2.Album color Theme
3.Caption selector
4.Discord Rich Presence
5.Downloader
6.In-App Menu
7.Genius Lyrics
8.Navigation
9.Scrobbler
10.Sponsor Block
11.Taskbar Media Control
12.Video Quality Changer

**Comment by JellyBrick** [comment] 2024-08-01 22:19
Duplicate of #1791

**Closed by JellyBrick** 2024-08-01 22:19 UTC
Labels: duplicate
