### ISSUE TITLE
[Bug]: Downloader does not work at all.

### ISSUE THREAD

**Issue by B0bq** [th-ch/youtube-music#2737] opened 2024-12-19 05:58 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.2 *tried on version 3.6.2 on portable and installed

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

I don't remember but it was in the 3.5.? area.

### Reproduction steps

1. Have downloader plugin enabled
2. Go to a public playlist
3. Download
4. Profit

### Expected Behavior

I expect it to create the folder and download all the songs and usually it would miss a couple songs here and with an invalid token.

### Actual Behavior

It creates the folder then when it starts downloading every single song has an error token and I can't download any of them.

### Enabled plugins

This is the list of plugins I ALWAYS use.
1. Adblocker
2. Ambient Mode
3. API Server
4. Crossfade
5. Downloader obviously
6. In-App Menu obviously
7. Navigation obviously
8. Precise Volume

### Additional Information

):

**Comment by JellyBrick** [comment] 2024-12-19 10:26
READ PREFLIGHT CHECKLIST

Duplicate of https://github.com/th-ch/youtube-music/issues/2691, https://github.com/th-ch/youtube-music/issues/2628, https://github.com/th-ch/youtube-music/issues/2700

**Closed by JellyBrick** 2024-12-19 10:26 UTC

**Comment by spoonh** [comment] 2024-12-19 22:30
https://github.com/th-ch/youtube-music/discussions/2726
