### ISSUE TITLE
[Feature Request]: Make Video Toggle defaults to Song or previous selection

### ISSUE THREAD

**Issue by CarterSnich** [th-ch/youtube-music#1904] opened 2024-03-29 05:29 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Video always plays by default when I just want to play music. But, sometimes I want to quickly watch the music's video, so I don't want to completely disable the video cos it also hides the music thumbnail.

### Proposed Solution

Add a default Video Toggle value (either Song or Video), or remember the previous selection.

### Alternatives Considered

If not possible, instead of completely removing the video, add an option to keep the music thumbnail for aesthetic purpose and making the song list's width a reasonable size.

This one looks better
![2024-03-29_13-25](https://github.com/th-ch/youtube-music/assets/52433531/6ad3fc45-a909-4443-8c3a-49c617efb7ef)

than this one.
![2024-03-29_13-26](https://github.com/th-ch/youtube-music/assets/52433531/f46d1054-6180-4119-a1cd-0647034bf8ed)

**Comment by ArjixWasTaken** [comment] 2024-03-29 05:53
You have not done the 2nd checkbox

**Comment by JellyBrick** [comment] 2024-03-29 11:55
Duplicate of #1383

**Closed by JellyBrick** 2024-03-29 11:55 UTC
