### ISSUE TITLE
[Bug]: Missing title/window bar on Linux

### ISSUE THREAD

**Issue by MulverineX** [th-ch/youtube-music#1479] opened 2023-12-02 17:19 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.0.1

### What operating system are you using?

Ubuntu

### Operating System Version

Pop OS 22.04

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

2.2.0

### Reproduction steps

1. Start in 2.2.0
2. Enable the in-app-menu plugin
3. Enable the custom title bar
4. Upgrade to 3.0.1

### Expected Behavior

The title bar should be shown & available.

### Actual Behavior

It is completely missing, the window ends at the top of the page

### Enabled plugins

- Discord RPC
- Adblock
- blur-nav-bar
- in-app-menu
- others (all except Adblock appear to now be disabled)

### Additional Information

Ran this command
```
sudo find / -name "*youtube*"
```

Uninstalled the app with the deb installer, deleted `/home/mulverine/.config/YouTube Music`, reinstalled.

It appears that the plugins I enabled are no longer enabled; Discord RPC is abscent, nav bar blur is missing, and yet the app still has no window bar, reverting to 2.2.0 fixes the problem, and none of my plugins are enabled, confirming that deleting the .config folder worked, and that its not a problem with my plugins.

![image](https://github.com/th-ch/youtube-music/assets/12068027/b124963d-c3d9-4e02-b1f3-2917c24a9ba9)
![image](https://github.com/th-ch/youtube-music/assets/12068027/83fc9060-7f55-40e9-959c-75b4beaa7d54)

**Comment by JellyBrick** [comment] 2023-12-02 17:50
Duplicate of #1478

**Closed** 2023-12-02 17:54 UTC
Labels: duplicate
