### ISSUE TITLE
Function to change output device?

### ISSUE THREAD

**Issue by Toximisity** [th-ch/youtube-music#418] opened 2021-09-29 18:50 UTC
I know the official app has the functionality in the settings menu to change output device, but this one does not. Yes, i know you can do this through standard windows settings, but if you close and reopen the app, it'll reset the output and input devices of the app, but checking the settings it shows that it is still on the correct audio track. Obviously switching between a different track and then back to the track i want it on fixes it, but it's super tedious to do that every time i start up my pc. Whether this is just a hidden feature that i haven't found, or something unintentionally or intentionally removed, i would appreciate either an addition or where to find the setting within the app.

**Comment by fedemox** [comment] 2022-07-04 11:01
The official WEB app (browser based) doesn't have this functionality either.
See issue #164

**Comment by JellyBrick** [comment] 2023-10-07 07:36
Duplicate of #164

**Closed by JellyBrick** 2023-10-07 07:36 UTC
