### ISSUE TITLE
[Feature Request]: Discord RPC Change status "Playing" to "Listening"

### ISSUE THREAD

**Issue by Dott-rus** [th-ch/youtube-music#2128] opened 2024-06-07 19:35 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Just add a function so that instead of "Playing", "Listening" is displayed in the Discord profile (just like in Spotify). It seems to be possible to implement because the Vencord plugin: "CustomRPC" has the ability to do such things.
![image](https://github.com/th-ch/youtube-music/assets/78660260/969c3208-c636-4feb-a70e-38dfb63d8260)

### Proposed Solution

Add the switch to the plugin settings

### Alternatives Considered

Or make this behavior by default

**Comment by JellyBrick** [comment] 2024-06-08 02:40
Duplicate of #1123 

See https://github.com/th-ch/youtube-music/pull/2052#issuecomment-2116593460

**Closed by JellyBrick** 2024-06-08 02:40 UTC
