### ISSUE TITLE
The app doesn't update music info correctly when music is not skipped.

### ISSUE THREAD

**Issue by FiestaLake** [th-ch/youtube-music#473] opened 2021-11-09 02:42 UTC
## Issue
App doesn't update the music info when the next music begins automatically. It breaks notification, discord, and pretty other stuffs that depend on it.

## Environment
Gnome 40.5, Arch Linux
youtube-music-bin 1.14.0-1

## How to reproduce
1. Play a music (playlist) and leave the app alone.
2. See whether app sends notification when the next music begins.

## How not to reproduce
1. Play the next music manually.

**Comment by Araxeus** [comment] 2021-11-09 08:16
Works perfectly fine for me, could you check that you are indeed using the last version?

This actually doesn't make much sense, I don't see any difference between "manual" or "automatic" track switching. the music info callback is called whenever the metadata is updated:
https://github.com/th-ch/youtube-music/blob/f40ed048995a5d22e9e3da7aa93d7a225755bc92/providers/song-info-front.js#L14

and also I find it very weird that only you complained about this app breaking bug

**Comment by FiestaLake** [comment] 2021-11-09 08:37
> Works perfectly fine for me, could you check that you are indeed using the last version?
> 
> This actually doesn't make much sense, I don't see any difference between "manual" or "automatic" track switching. the music info callback is called whenever the metadata is updated:
> 
> https://github.com/th-ch/youtube-music/blob/f40ed048995a5d22e9e3da7aa93d7a225755bc92/providers/song-info-front.js#L14
> 
> and also I find it very weird that only you complained about this app breaking bug

[Video verification](https://youtu.be/Nzl7Pka8wjo)
Yes, I'm running latest AUR version; youtube-music-bin 1.14.0-1
I really like your app. I always use it and find it nice. Please do not think I like complaining and tackling :)

**Comment by bytang** [comment] 2021-11-09 13:24
I think I am experiencing the same behaviour. I am running 1.14 on Windows and I see this behaviour in Last.fm scrobbling.

![image](https://user-images.githubusercontent.com/3239663/140929876-4ae5a6c4-5851-4394-9f4b-c096dedfad0a.png)

It scrobbles the same song 3 times while the playlist goes through three different songs. If I skip to next song, it scrobbles the new song as intended (not shown in screenshot).

I use last-fm and navigation plugins. I tried a clean reinstall and it is the same behaviour.

**Comment by Araxeus** [comment] 2021-11-09 16:05
@bytang thank you for confirming this issue. i've been working on it and testing with the help of @FiestaLake  and after many hours and tries we have found a fix.

PR #477 implement said fix and will hopefully be soon merged :)

**Closed** 2021-11-29 22:52 UTC
