### ISSUE TITLE
[Feature Request]: disable music videos from playing.

### ISSUE THREAD

**Issue by nex8928** [th-ch/youtube-music#1874] opened 2024-03-20 13:53 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When playing a playlist on YouTube Music, it often plays the video version of a song. 

### Proposed Solution

There should be an option to disable this and play the audio-only version of the song instead.

### Alternatives Considered

Disable playing video.

**Comment by JellyBrick** [comment] 2024-03-23 15:39
Duplicate of #1383

**Closed by JellyBrick** 2024-03-23 15:39 UTC
