### ISSUE TITLE
[Feature Request]: create a flatpak package

### ISSUE THREAD

**Issue by Katze719** [th-ch/youtube-music#1934] opened 2024-04-04 16:44 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

it would be nice to download the app via flatpak

### Proposed Solution

make a flatpak

### Alternatives Considered

using the rpm version also works for me

**Comment by JellyBrick** [comment] 2024-04-04 17:16
![image](https://github.com/th-ch/youtube-music/assets/16558115/fe399145-a23d-47cc-9932-cc2d5acd1a32)
![image](https://github.com/th-ch/youtube-music/assets/16558115/ee14ff3b-ef53-486a-a282-4ce30ebdd5ba)


Duplicate of #737

**Closed by JellyBrick** 2024-04-04 17:16 UTC

**Comment by Katze719** [comment] 2024-04-04 17:25
damn, did actually not show up when searching for flatpak in the issues section
