### ISSUE TITLE
[Bug]: Music Together not working

### ISSUE THREAD

**Issue by bedeee123** [th-ch/youtube-music#2513] opened 2024-10-15 18:00 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.1

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

11

### What CPU architecture are you using?

x64

### Last Known Working YouTube Music (Application) version

3.5

### Reproduction steps

1. Join a music together session

### Expected Behavior

Can play music together

### Actual Behavior

The plugin just keeps loading and cant connect to the session
![image](https://github.com/user-attachments/assets/f77fc919-2480-4ca4-a724-337b50f66d09)

### Enabled plugins

1. Music Together
2. Exponential volume
3. synced lyrics

**Comment by JellyBrick** [comment] 2024-10-16 11:18
Duplicate of #2407

**Closed by JellyBrick** 2024-10-16 11:18 UTC
