### ISSUE TITLE
[Bug]: Mac arm app is damaged

### ISSUE THREAD

**Issue by ishaanrathodd** [th-ch/youtube-music#2362] opened 2024-08-20 18:57 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

macOS Sonoma 14.6

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Reproduction steps

Just open the arm64 dmg app

### Expected Behavior

Should open

### Actual Behavior

<img width="266" alt="image" src="https://github.com/user-attachments/assets/685404b3-471f-4183-b4f3-901f5d4792fc">

### Enabled plugins

None

**Comment by JellyBrick** [comment] 2024-08-20 22:58
Duplicate of #186

**Closed by JellyBrick** 2024-08-20 22:58 UTC

**Comment by ishaanrathodd** [comment] 2024-08-21 03:25
> Duplicate of #186

@JellyBrick btw these two errors aren't same. Developer cannot be verified error can be easily bypassed through settings, but if the .dmg is damaged, the app cannot be opened in any possible way because it's broken.

**Comment by JellyBrick** [comment] 2024-08-21 03:36
> > Duplicate of #186
> 
> @JellyBrick btw this is not a duplicate thread of the one you mentioned and these two errors aren't same. Developer cannot be verified error can be easily bypassed through settings, but if the .dmg is damaged, the app cannot be opened in any possible way because it's broken.

No. It's duplicated.

See https://github.com/th-ch/youtube-music/issues/2146#issuecomment-2191636736
See https://github.com/th-ch/youtube-music/issues/1605
See https://github.com/th-ch/youtube-music/issues/1243
