### ISSUE TITLE
[Bug]: Ad-block "blocklists" Mode Prevents App Loading

### ISSUE THREAD

**Issue by Ao1Pointblank** [th-ch/youtube-music#1269] opened 2023-10-07 15:38 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [ ] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.

### YouTube Music (Application) Version

2.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux Mint 21.2

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

1.20.0

### Expected Behavior

App loads without ads and plays music

### Actual Behavior

When using the adblocker in "blocklists" mode, the app won't start properly, just a black window showing only the plugins/options/view/navigation menu bar at the top

### Additional Information

Using "in player" mode works fine, but since "blocklists" is the default when first enabling the plugin, it will result in some confused users.

**Comment by JellyBrick** [comment] 2023-10-07 15:43
Duplicate of #1267

**Comment by JellyBrick** [comment] 2023-10-07 15:49
v2.0.1 has been released with a temporary fix for this issue. This is not a complete fix, so I will keep the issue open until the issue is fully resolved.

**Comment by JellyBrick** [comment] 2023-10-07 15:54
v1.20.0 also appears to be affected.

**Closed** 2023-10-09 10:52 UTC
Labels: bug, fix-available
