### ISSUE TITLE
[Feature Request]: Use downloaded music if there are 

### ISSUE THREAD

**Issue by mohrazzak** [th-ch/youtube-music#1407] opened 2023-11-13 10:21 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I am wondering if it is possible to have a plugin that checks for downloaded music 
if it exists then you don't have to use internet to listen it 

### Proposed Solution

idk

### Alternatives Considered

idk

**Comment by JellyBrick** [comment] 2023-11-13 12:07
Duplicate of #874

**Closed by JellyBrick** 2023-11-13 12:07 UTC
Labels: duplicate
