### ISSUE TITLE
last.fm plugin reporting wrong titles / not scrobbling

### ISSUE THREAD

**Issue by Call190Now** [th-ch/youtube-music#266] opened 2021-05-09 19:03 UTC
Few days ago I noticed that last.fm plugin wasn't properly scrobbling my tracks and the now playing was using a title from the following track on that playlist, like this:
![image_2021-05-09_15-48-32](https://user-images.githubusercontent.com/6476176/117583836-d0ab1280-b0df-11eb-910f-04d14eb9d11a.png)

also, thanks for the nice job with this wrapper, it's definitely one of the best youtube-music clients I've used.

**Comment by Araxeus** [comment] 2021-05-09 19:29
Can you try enabling the `notifications` plugin and see if the error shows up on notifications too?

**Comment by Call190Now** [comment] 2021-05-09 19:48
> Does this happen on every track? or just the first one?
> 
> Can you try enabling the `notifications` plugin and see if the error shows up on notifications too?
> 
> > this is really weird.. there shouldn't be any data about the next song before it starts playing

seems to be happening on every track, rarely happens on the first track to be honest. About the notifications, yes, same problem.

![Captura de tela de 2021-05-09 16-46-28](https://user-images.githubusercontent.com/6476176/117584968-4e721c80-b0e6-11eb-8926-caeb040de17f.png)

**Comment by Araxeus** [comment] 2021-05-09 20:05
I'm sorry I really have no idea how this is possible. and I really can't reproduce it..

songInfo is gotten from XML Http Request that the page makes when loading a song.
It should only contains info about the current video that is played..

@th-ch @semvis123 
Maybe you have an idea as to how this is even possible?

I could try fixing it by parsing song title like we already parse the song artist (directly from the playbar html element). but we should probably know first why this is even happening

**Comment by semvis123** [comment] 2021-05-09 20:20
Definitely interesting.
Your computer seems to be predicting the future :)

I'm also not able to reproduce this issue myself.
To me it looks like that the http request is made in preparation of the next song (maybe because it detected good enough internet?) which updates the song information provider with the information of the next song. 

Did this started happening recently? What version are you running?
Does this still happen after a force reload?

**Comment by Araxeus** [comment] 2021-05-10 01:30
You can find force reload in 
> "Menu -> View -> Force Reload"

Could you try cloning the [branch](https://github.com/Araxeus/youtube-music/tree/override-song-info-option) from my [PR](https://github.com/th-ch/youtube-music/pull/268) and enable Override SongInfo to see if that solved it for you?
> "Menu - Options - Advanced Options - Override SongInfo"

**Comment by Call190Now** [comment] 2021-05-10 02:22
> You can find force reload in
> 
> > "Menu -> View -> Force Reload"
> 
> Could you try cloning the [branch](https://github.com/Araxeus/youtube-music/tree/override-song-info-option) from my [PR](https://github.com/th-ch/youtube-music/pull/268) and enable Override SongInfo to see if that solved it for you?
> 
> > "Menu -> Options -> Advanced Options -> Override SongInfo"

seems to be fine after overriding songinfo! 
![image](https://user-images.githubusercontent.com/6476176/117595765-11bf1900-b118-11eb-863a-c9574be77988.png)

**Comment by Call190Now** [comment] 2021-05-10 02:22
after some further testing I decided to delete all Youtube Music data from .config and weirdly enough it started to work fine and my scrobbles are actually being counted now. Should I close this issue?

**Comment by Call190Now** [comment] 2021-05-10 02:30
> @Call190Now are you saying that the new "Override SongInfo" is not necessary?
> does it work with the main branch/release or only with my branch?

sorry if I wasn't clear but yeah, it's working fine without Override SongInfo, thanks for the help

**Comment by Araxeus** [comment] 2021-05-10 02:40
I'm glad that worked out.
I think you can safely close the issue 🙂

**Closed** 2021-05-10 02:41 UTC

**Comment by FiestaLake** [comment] 2021-06-22 05:48
I face similar issue with notification. It shows something like this:
![image](https://user-images.githubusercontent.com/68979855/122870636-e2cbd200-d368-11eb-8c08-928104b2d654.png)
