### ISSUE TITLE
[Bug]: Audio distortion from Crossfade plugin

### ISSUE THREAD

**Issue by KubaPro010** [th-ch/youtube-music#2296] opened 2024-07-31 18:52 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Enable crossfade
2. Play any song

### Expected Behavior

Good sounding audio

### Actual Behavior

Somewhat distorted audio (its subtle but for my purpose it is completly non-usable)

### Enabled plugins

1. Adblocker
2. Audio Compressor
3. (Crossfade)
4. In-App Menu
5. Navigation
6. Skip Silences (i though this one would do the distortion)
7. Sponsorblock

### Additional Information

I intend this issue to track the bug, to also check when it is gone
EDIT: at the 2nd song, similiar distortion comes on despite crossfade being on or off

**Comment by JellyBrick** [comment] 2024-07-31 22:15
Duplicate of #1148

**Closed by JellyBrick** 2024-07-31 22:15 UTC
Labels: duplicate
