### ISSUE TITLE
Album cover turning black while plugin 'bypass-age-restrictions' is turned on

### ISSUE THREAD

**Issue by Hooooooman** [th-ch/youtube-music#1205] opened 2023-07-16 08:42 UTC
version: 1.20.0
![image](https://github.com/th-ch/youtube-music/assets/91048741/5d08fc86-954b-4c9d-ba3b-8b88df002007)
![image](https://github.com/th-ch/youtube-music/assets/91048741/04ac48f5-884c-4363-a000-56d8c2440743)

**Comment by Zastando** [comment] 2023-07-16 11:10
Duplicate of https://github.com/th-ch/youtube-music/issues/1177, https://github.com/th-ch/youtube-music/issues/1194 and https://github.com/th-ch/youtube-music/issues/1196.

**Closed** 2023-09-03 17:38 UTC
