### ISSUE TITLE
[Bug]: lyrics dont found when i use synced lyrics.

### ISSUE THREAD

**Issue by dnsouzadev** [th-ch/youtube-music#2391] opened 2024-09-05 20:36 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.5.1

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [X] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other Linux

### Operating System Version

POP Os

### What CPU architecture are you using?

x64

### Reproduction steps

dont found any lyrics

### Expected Behavior

a expected the lyric

### Actual Behavior

dont show

### Enabled plugins

album actions
navigation
synced lyrics

**Comment by ArjixWasTaken** [comment] 2024-09-05 20:46
![image](https://github.com/user-attachments/assets/94e651a0-cea7-4b39-a7ea-44d754eb509f)

**Comment by dnsouzadev** [comment] 2024-09-05 22:11
![image](https://github.com/user-attachments/assets/22591098-301a-4d60-9a4b-5361ae2ae93e)

any song that i try dont show.

**Comment by derfurkan** [comment] 2024-09-05 23:54
> ![image](https://private-user-images.githubusercontent.com/53124886/364945069-94e651a0-cea7-4b39-a7ea-44d754eb509f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODA3MDMsIm5iZiI6MTcyNTU4MDQwMywicGF0aCI6Ii81MzEyNDg4Ni8zNjQ5NDUwNjktOTRlNjUxYTAtY2VhNy00YjM5LWE3ZWEtNDRkNzU0ZWI1MDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDIzNTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMzU3NzYyNTFkNTY1ZDUyNzUwYjUzMWE5NDkxZWE4NzkxNDczMjg3NmQwN2YyYjFlYTQ5NGRiZWI3ODYzMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qXMPsnlBXGa0DrsgjNshw0exo0pL7Smgu5FlP99VXaY)

Believe me when i say that i feel your pain

**Comment by JellyBrick** [comment] 2024-09-07 09:31
Duplicate of #2367

**Closed by JellyBrick** 2024-09-07 09:31 UTC
