### ISSUE TITLE
UI stopped working

### ISSUE THREAD

**Issue by banks047** [th-ch/youtube-music#581] opened 2022-01-28 21:02 UTC
Hi there. I'd like to report an issue. 
I'm having an issue where the app stopped loading ui. It used to work on first run and now it does not, but even though it doesn't show ui, music starts playing in the background. I've tried AppImage and rpm versions and they behave exactly the same
I'm using Fedora 35 Workstation and here's the log from terminal:
![image](https://user-images.githubusercontent.com/64637377/151620883-9305a2ed-4526-4539-8475-c1ce369a6ebb.png)

Per this log, there doesn't seem to be any error when launching. Please let me know which information do you need so we can troubleshoot this.
Thanks in advance!

EDIT: App version 1.15.0

**Comment by Araxeus** [comment] 2022-01-29 06:46
Hey this is probably because your window position is offscreen 
(was already fixed in #548 and will be included in next release)

meanwhile to fix it you can:
open config.json and change window position to be like (0,0)

> config.json folder path:
> * Windows: `%AppData%/Youtube Music` (MyUser/AppData/Roaming/Youtube Music)
> * Linux: `~/.config/Youtube Music`
> * MacOS: `~/Library/Application\ Support/YouTube\ Music/config.json`

**Comment by banks047** [comment] 2022-01-29 11:00
Hi, thanks for fast response!
I've tried to change the window position to (0,0) but it still behaved exactly the same :/ 
I wasn't aware that commit #548 was not included in 1.15 release, i'll try building a more recent version and see how it goes.
PS. I'm using dual monitor setup

**Comment by Araxeus** [comment] 2022-01-29 11:45
could be maybe related to the error you seem to get `APPIMAGE env not defined. current application is not an AppImage`

not sure how to fix that error, dont know where is it even coming from.. 

could maybe be coming from the  Auto-update option, could you try disabling that and see if it changes something?

**Comment by banks047** [comment] 2022-01-29 15:55
I've wiped the config files from `~/.config/Youtube Music` and it started working again. `config.json` doesn't seem to be much different (other than appVisible being true in working version and false in not working but changing true to false in the working version doesn't do anything) so i think that the culprit is among other files. I'll investigate further and let you know my findings.

**Comment by Araxeus** [comment] 2022-01-29 16:12
Good catch! 

obviously not a good idea to set the app as tray only when you dont have a tray 😅

**Comment by banks047** [comment] 2022-01-29 16:15
I agree! 
It's really worrying that this happens, considering GNOME is the main desktop environment on the most popular Linux distros. I guess we can't do anything about that, but add a disclaimer and a workaround somewhere in README

**Comment by piezza** [comment] 2023-10-08 07:47
I am not sure if this is same root cause but I have similar problem under Windows 11 that UI is not shown with newest version and App runs in background playing music and I need to stop over task manager.
With v1.20.0 everything works fine, starting with v2.0.0 I have this issue. Also removing `%AppData%/Youtube Music` does not fix this.

**Comment by JellyBrick** [comment] 2023-10-08 08:18
> I am not sure if this is same root cause but I have similar problem under Windows 11 that UI is not shown with newest version and App runs in background playing music and I need to stop over task manager. With v1.20.0 everything works fine, starting with v2.0.0 I have this issue. Also removing `%AppData%/Youtube Music` does not fix this.

That issue is being tracked in #1273.

**Comment by JellyBrick** [comment] 2023-10-09 13:31
Fixed due to https://github.com/electron/electron/pull/23926

**Closed by JellyBrick** 2023-10-09 13:31 UTC
Labels: bug, wontfix
