### ISSUE TITLE
[Bug]: donwloader plugin podcast playlist "Error: playlist is empty"

### ISSUE THREAD

**Issue by gorgia** [th-ch/youtube-music#2257] opened 2024-07-18 14:28 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.4.1.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What CPU architecture are you using?

x64

### Reproduction steps

1: Enable the downloader plugin
2: Select any podcast playlist
3: Try to use the plugin downloader

### Expected Behavior

Same as songs playlist.

### Actual Behavior

Error: playlist is empty

### Enabled plugins

1: Dowloader

### Additional Information

I've tried with many podcast channels and playlists

**Comment by neolight1010** [comment] 2024-07-29 15:40
This seems to be a duplicate of #2234 .

**Closed** 2024-07-29 22:12 UTC
Labels: duplicate
