### ISSUE TITLE
[Feature Request]: Way to control yt music specific features outside the app

### ISSUE THREAD

**Issue by Readf0x** [th-ch/youtube-music#1674] opened 2024-01-24 02:11 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Personally, I use [eww](https://github.com/elkowar/eww) for my status bar, and I built this wonderful media widget in it.
<details>
<summary>Screenshot for proof:</summary>

![image](https://github.com/th-ch/youtube-music/assets/57838054/05ae4afc-c979-4459-b647-4919ea7df497)
</details>
I've been looking for a way to add like, dislike, and/or (maybe) shuffle and repeat buttons. The only problem is, I have no way to control those outside of the app. Not even the tray icon has shortcuts for them (I would've even tried to figure out how to fake inputs from the tray icon to make that work). A way to control these app-specific features, that aren't supported by mpris or xesam, would be amazing. If added, it should report whether or not said controls are active, and provide a method to toggle them.

### Proposed Solution

There are many possible options, but simplest one for users to implement into their setups would be some kind of terminal ctl. This would likely not be very easy to add into the project, as it's at a far lower level than most of the existing features.

### Alternatives Considered

Off the top of my head, I can think of a number of alternative ways to accomplish this.
- A dbus interface (great for compatibility with all kinds of programs)
- A server based api, like the one used by [ytmdesktop](https://github.com/ytmdesktop/ytmdesktop). This was also proposed in #1094
- As previously mentioned, tray controls (also available in ytmdesktop)

That's all I can think of immediately, but there are likely other options as well.

**Comment by inson1** [comment] 2024-01-24 08:48
there is gonna be rest api https://github.com/th-ch/youtube-music/discussions/1650#discussioncomment-8153540

**Comment by Destroy666x** [comment] 2024-01-24 15:56
This is a dupe of many issues/PRs/discussions. I'm currently working on a PR for REST API, I'll likely finish it before the end of the month, if I find enough free time.

**Comment by Readf0x** [comment] 2024-01-24 16:53
> This is a dupe of many issues/PRs/discussions.

I don't have permission to manage labels, could someone close this as duplicate?

> I'm currently working on a PR for REST API, I'll likely finish it before the end of the month, if I find enough free time.

Send me a link?

**Comment by ArjixWasTaken** [comment] 2024-01-24 17:31
@Readf0x 

Related to: #1581, #1650, #1566
Dead PRs: #1151, #767, #1094

**Comment by ArjixWasTaken** [comment] 2024-01-24 17:32
@Destroy666x 

If you don't have a lot of fine, it is always an option to open a draft PR and receive help from us.
At least I am willing to help, dunno the schedule of the others.

**Comment by ArjixWasTaken** [comment] 2024-01-24 17:32
Closing as duplicate

**Closed by ArjixWasTaken** 2024-01-24 17:32 UTC
