### ISSUE TITLE
[Bug]: Ubuntu 24.10 (linux 6.11 , Gnome 47) needs "--no-sandboox"

### ISSUE THREAD

**Issue by nastiliano** [th-ch/youtube-music#2512] opened 2024-10-15 17:36 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.6.1

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 24.10

### What CPU architecture are you using?

x64

### Reproduction steps

Launch the app

### Expected Behavior

Launching directly

### Actual Behavior

The app only works launched from terminal with "--no-sandbox" option

### Enabled plugins

Nothing

**Comment by JellyBrick** [comment] 2024-10-16 11:16
Duplicate of #2007

**Closed by JellyBrick** 2024-10-16 11:16 UTC
Labels: duplicate

**Comment by nastiliano** [comment] 2024-10-16 12:20
> Duplicate of #2007

Upps!
Thank you very much
