### ISSUE TITLE
[Bug]: Windows defender triggered with the latest portable version

### ISSUE THREAD

**Issue by cr0sss4ns** [th-ch/youtube-music#2131] opened 2024-06-08 13:11 UTC
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 pro version 23H2 build 22631.3447

### What CPU architecture are you using?

x64

### Reproduction steps

Download the latest portable version

### Expected Behavior

Launch the exe

### Actual Behavior

Windows recognize it like a virus

### Enabled plugins

Not applicable

### Additional Information

I don't know why, but when I try to download the latest portable version, windows defender is triggered, it's not appended with the previous version.
![image](https://github.com/th-ch/youtube-music/assets/105844196/94b483c2-2a79-4de9-a1b0-1ab4e16f56dc)
![image](https://github.com/th-ch/youtube-music/assets/105844196/7bc34264-4ff2-4db2-8281-092542e3c67e)

**Comment by mmcmd** [comment] 2024-06-08 13:43
Same issue here
![image](https://github.com/th-ch/youtube-music/assets/36875145/c345f81c-4c57-438c-a360-04c1f8f8da52)

**Comment by djlivooo** [comment] 2024-06-08 14:46
![image](https://github.com/th-ch/youtube-music/assets/98977517/04a67d9e-748d-45f9-8b3f-7a15bfc29ae0)
Same here

**Comment by jorbig** [comment] 2024-06-08 17:31
Microsoft Defender sees it as a severe threat:

![image](https://github.com/th-ch/youtube-music/assets/49766553/9b683fb9-a0ab-4f10-b5a5-04f76f05646c)

**Comment by JellyBrick** [comment] 2024-06-09 09:35
Duplicate of #1830

**Closed by JellyBrick** 2024-06-09 09:35 UTC
