### ISSUE TITLE
Ads playing all of a sudden 

### ISSUE THREAD

**Issue by nascentt** [th-ch/youtube-music#1839] opened 2024-03-07 11:10 UTC
Been using YouTube music for years, but today I just had ads between songs.

"Sponsored - video will play after ad"
AD Blocker: Enabled
Auto Update: Enabled 
Version: 3.3.2.0

**Comment by JellyBrick** [comment] 2024-03-07 11:33
Duplicate of #1817

**Closed by JellyBrick** 2024-03-07 11:33 UTC
